Repository Kushal997-das/Project-Guidance, pull requests merged in 2021-01, with the labels that each got.

#22 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement

#28 added a new project called guess the word
  Desktop Application/Basic/Python/Guess The Word/GTW.gif
  Desktop Application/Basic/Python/Guess The Word/GTW.py
  Desktop Application/Basic/Python/Guess The Word/README.md
Labels: enhancement

#47 Shopping List Project
  Desktop Application/Basic/C++/README.md
  Desktop Application/Basic/C++/Shopping List/README.md
  Desktop Application/Basic/C++/Shopping List/Shopping-Image.png
  Desktop Application/Basic/C++/Shopping List/main.cpp
Labels: Added Project, Fixed Bug, Open source, documentation, enhancement

#53 Red Black Tree Project
  Desktop Application/Advanced/Java/README.md
  Desktop Application/Advanced/Java/Red Black Tree GUI/.classpath
  Desktop Application/Advanced/Java/Red Black Tree GUI/.project
  Desktop Application/Advanced/Java/Red Black Tree GUI/.settings/org.eclipse.jdt.core.prefs
  Desktop Application/Advanced/Java/Red Black Tree GUI/Image-rbt.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/README.md
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/Main$1.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/Main$2.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/Main$3.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/Main$4.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/Main.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/MainPanel.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/rbt/Node.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/rbt/RedBlackTree.class
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/res/rbt_icon.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/res/rbt_icon_clear.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/res/rbt_icon_insert.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/bin/res/rbt_icon_remove.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/Main.java
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/MainPanel.java
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/rbt/Node.java
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/rbt/RedBlackTree.java
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/res/rbt_icon.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/res/rbt_icon_clear.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/res/rbt_icon_insert.png
  Desktop Application/Advanced/Java/Red Black Tree GUI/src/res/rbt_icon_remove.png
Labels: Added Project, Open source, documentation, enhancement

#55 Queue Visualizer Project
  Desktop Application/Basic/C++/Queue Visualizer/How to use.txt
  Desktop Application/Basic/C++/Queue Visualizer/Readme.md
  Desktop Application/Basic/C++/Queue Visualizer/queue visualizer.cpp
  Desktop Application/Basic/C++/Queue Visualizer/screenshots/Screenshot 2021-01-25 213908.png
  Desktop Application/Basic/C++/Queue Visualizer/screenshots/Screenshot 2021-01-25 214000.png
  Desktop Application/Basic/C++/Queue Visualizer/screenshots/Screenshot 2021-01-25 214020.png
Labels: Added Project, Fixed Bug, Open source, Updating Project, documentation, enhancement

#57 Router Synchronization Project
  Desktop Application/Advanced/Java/Red Black Tree GUI/README.md
  Desktop Application/Basic/C++/Shopping List/README.md
  Desktop Application/Intermediate/Java/README.md
  Desktop Application/Intermediate/Java/Router Synchronization/.classpath
  Desktop Application/Intermediate/Java/Router Synchronization/.project
  Desktop Application/Intermediate/Java/Router Synchronization/.settings/org.eclipse.jdt.core.prefs
  Desktop Application/Intermediate/Java/Router Synchronization/README.md
  Desktop Application/Intermediate/Java/Router Synchronization/Router S-Img.png
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/DeviceClass.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/FileClasse.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/NetworkClass.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/OutputGUI.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/RouterClass.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/RouterGUI$1.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/RouterGUI.class
  Desktop Application/Intermediate/Java/Router Synchronization/bin/synchronizationPackage/SemaphoreClass.class
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/DeviceClass.java
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/FileClasse.java
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/NetworkClass.java
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/OutputGUI.java
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/RouterClass.java
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/RouterGUI.java
  Desktop Application/Intermediate/Java/Router Synchronization/src/synchronizationPackage/SemaphoreClass.java
  Web Development/Advanced/Hotel Reservation System/README.md
Labels: Under-review, Work-in-progress

#60 CMD Project
  Desktop Application/Intermediate/Java/CMD/.classpath
  Desktop Application/Intermediate/Java/CMD/.project
  Desktop Application/Intermediate/Java/CMD/.settings/org.eclipse.jdt.core.prefs
  Desktop Application/Intermediate/Java/CMD/CMD-Image.png
  Desktop Application/Intermediate/Java/CMD/README.md
  Desktop Application/Intermediate/Java/CMD/bin/main/Main.class
  Desktop Application/Intermediate/Java/CMD/bin/main/Parser.class
  Desktop Application/Intermediate/Java/CMD/bin/main/Terminal.class
  Desktop Application/Intermediate/Java/CMD/bin/major/Parser.class
  Desktop Application/Intermediate/Java/CMD/bin/major/Terminal.class
  Desktop Application/Intermediate/Java/CMD/src/main/Main.class
  Desktop Application/Intermediate/Java/CMD/src/main/Main.java
  Desktop Application/Intermediate/Java/CMD/src/main/Parser.class
  Desktop Application/Intermediate/Java/CMD/src/main/Parser.java
  Desktop Application/Intermediate/Java/CMD/src/main/Terminal.class
  Desktop Application/Intermediate/Java/CMD/src/main/Terminal.java
Labels: Added Project, Open source, documentation, enhancement
