Repository Kushal997-das/Project-Guidance, pull requests merged in 2021-02, with the labels that each got.

#80 New Desktop Project Added - SQL [ Recruitment System ]
  Desktop Application/Basic/SQL/Recruitment System/Project Models/ERD.png
  Desktop Application/Basic/SQL/Recruitment System/Project Models/Physical Model.png
  Desktop Application/Basic/SQL/Recruitment System/Project Queries/Query 1.png
  Desktop Application/Basic/SQL/Recruitment System/Project Queries/Query 2.png
  Desktop Application/Basic/SQL/Recruitment System/Project Queries/Query 3.png
  Desktop Application/Basic/SQL/Recruitment System/Project Queries/Query 4.png
  Desktop Application/Basic/SQL/Recruitment System/Project Queries/Query 5.png
  Desktop Application/Basic/SQL/Recruitment System/Project Queries/Query 6.png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Add a new vacancy.png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Apply and save vacancy (job seeker).png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Showing a list of job seekers that satisfy certain criteria.png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Showing a list of vacancies that satisfy certain criteria.png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Signing up a new user (employer).png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Signing up a new user (job seeker).png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Update user (employer).png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Update user (job seeker).png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/Update vacancy.png
  Desktop Application/Basic/SQL/Recruitment System/Project functions/hide vacancy (employer).png
  Desktop Application/Basic/SQL/Recruitment System/README.md
  Desktop Application/Basic/SQL/Recruitment System/SQL Scripts.sql
Labels: Under-review, Work-in-progress

#82 Small Contributions in web project -> Tourist Places
  CONTRIBUTING.md
  Documents/Clone-Image.png
  Documents/Clone-Link-Image.png
  Documents/Fork-Image.png
  Web Development/Basic/Tourist Places/index.html
Labels: Work-in-progress

#83 Web Dev README Updated
  Web Development/README.md
Labels: Under-review, Updating Project, Work-in-progress, bug, documentation

#87 DB File Added [MySQL]
  Web Development/Advanced/Hotel Reservation System/DB/Dump20210115.sql
Labels: Under-review, Work-in-progress, enhancement

#91 Updates in shopping list project -> C++
  Desktop Application/Basic/C++/Shopping List/README.md
  Desktop Application/Basic/C++/Shopping List/main.cpp
Labels: Updating Project, enhancement

#96 BrickBreaker Game added
  Desktop Application/Basic/Java/BrickBreaker/src/BrickBreaker_gif.gif
  Desktop Application/Basic/Java/BrickBreaker/src/GamePlay.java
  Desktop Application/Basic/Java/BrickBreaker/src/Main.java
  Desktop Application/Basic/Java/BrickBreaker/src/MapGenerator.java
  Desktop Application/Basic/Java/BrickBreaker/src/README.md
Labels: Added Project, Firstcontribution, documentation, enhancement

#101 B-Tree File Project [C++]
  Desktop Application/Intermediate/C++/B-Tree File Indexing/B-Tree-Files-Image.png
  Desktop Application/Intermediate/C++/B-Tree File Indexing/README.md
  Desktop Application/Intermediate/C++/B-Tree File Indexing/main.cpp
  Desktop Application/Intermediate/C++/README.md
Labels: Added Project, documentation, enhancement

#106 Recruitment System Updates
  Desktop Application/Basic/SQL/Recruitment System/README.md
  Desktop Application/Basic/SQL/Recruitment System/SQL Scripts.sql
  README.md
Labels: Open source, documentation, enhancement

#109 Code Enhancements
  Web Development/Basic/Tourist Places/Aboutus.html
  Web Development/Basic/Tourist Places/Activities.html
  Web Development/Basic/Tourist Places/Contactus.html
  Web Development/Basic/Tourist Places/andamaan.html
  Web Development/Basic/Tourist Places/bestimetovisit.html
Labels: Fixed Bug, Updating Project, enhancement

#110 Create greetings.yml
  .github/workflows/greetings.yml
Labels: enhancement

#120 Feat: code enhancements
  Web Development/Advanced/Hotel Reservation System/web/reservations.jsp
  Web Development/Advanced/Hotel Reservation System/web/reservationsClient.jsp
  Web Development/Advanced/Hotel Reservation System/web/rooms.jsp
  Web Development/Advanced/Hotel Reservation System/web/updateHotel.jsp
  Web Development/Advanced/Hotel Reservation System/web/updateHotelImages.jsp
Labels: enhancement

#124 Feat/code enhancements
  Web Development/Advanced/Hotel Reservation System/src/java/addHotel.java
  Web Development/Advanced/Hotel Reservation System/src/java/addHotelImages.java
  Web Development/Advanced/Hotel Reservation System/src/java/addRate.java
  Web Development/Advanced/Hotel Reservation System/src/java/addRoom.java
  Web Development/Advanced/Hotel Reservation System/src/java/cancelReservation.java
Labels: Updating Project, enhancement

#125 Feat: Code enhancements
  Web Development/Advanced/Hotel Reservation System/src/java/cancelReservationClient.java
  Web Development/Advanced/Hotel Reservation System/src/java/changeProfileData.java
  Web Development/Advanced/Hotel Reservation System/src/java/changeReservation.java
  Web Development/Advanced/Hotel Reservation System/src/java/confirmReservation.java
  Web Development/Advanced/Hotel Reservation System/src/java/filterDistance.java
Labels: Updating Project

#128 Feat: Add spring boot project
  Desktop Application/Intermediate/Java/Mail API/.mvn/wrapper/MavenWrapperDownloader.java
  Desktop Application/Intermediate/Java/Mail API/.mvn/wrapper/maven-wrapper.jar
  Desktop Application/Intermediate/Java/Mail API/.mvn/wrapper/maven-wrapper.properties
  Desktop Application/Intermediate/Java/Mail API/README.md
  Desktop Application/Intermediate/Java/Mail API/jty-mail-img.png
  Desktop Application/Intermediate/Java/Mail API/mvnw
  Desktop Application/Intermediate/Java/Mail API/mvnw.cmd
  Desktop Application/Intermediate/Java/Mail API/pom.xml
  Desktop Application/Intermediate/Java/Mail API/src/main/java/com/mail/jty/JtyMail/JtyMailApplication.java
  Desktop Application/Intermediate/Java/Mail API/src/main/java/com/mail/jty/JtyMail/api/MailController.java
  Desktop Application/Intermediate/Java/Mail API/src/main/java/com/mail/jty/JtyMail/dao/MailDataAccessLayer.java
  Desktop Application/Intermediate/Java/Mail API/src/main/java/com/mail/jty/JtyMail/dao/MailDataAccessLayerClass.java
  Desktop Application/Intermediate/Java/Mail API/src/main/java/com/mail/jty/JtyMail/service/MailService.java
  Desktop Application/Intermediate/Java/Mail API/src/main/resources/application.properties
  Desktop Application/Intermediate/Java/Mail API/src/test/java/com/mail/jty/JtyMail/JtyMailApplicationTests.java
Labels: Updating Project

#129 Update README.md
  README.md
Labels: Updating Project, enhancement
