Repository Kushal997-das/Project-Guidance, pull requests merged in 2021-06, with the labels that each got.

#156 fix few bug
  Desktop Application/README.md
Labels: Fixed Bug

#155 Add files via upload
  Machine Learning and Data Science/Intermediate/Iriswebapp-main/Procfile
  Machine Learning and Data Science/Intermediate/Iriswebapp-main/README.md
  Machine Learning and Data Science/Intermediate/Iriswebapp-main/app.py
  Machine Learning and Data Science/Intermediate/Iriswebapp-main/requirements.txt
  Machine Learning and Data Science/Intermediate/Iriswebapp-main/setup.sh
Labels: Under-review

#158 Added New logo
  Documents/Project Guidance (2).gif
  README.md
Labels: documentation
