Repository Kushal997-das/Project-Guidance, pull requests merged in 2021-10, with the labels that each got.

#175 AI/ML
  Machine Learning and Data Science/Advanced/Detox/Intelligent_Garbage_Management_System_Model_Development.ipynb
  Machine Learning and Data Science/Advanced/Detox/ReadMe.md
Labels: Added Project, Updating Project, Firstcontribution, hacktoberfest-acepted

#176 Web Development Basic Project Added (Done That Under Hacktoberfest 2021)
  Web Development/Basic/Google Clone/README.md
  Web Development/Basic/Google Clone/googleclone.css
  Web Development/Basic/Google Clone/images/accountIcon.png
  Web Development/Basic/Google Clone/images/googleIcon.jpg
  Web Development/Basic/Google Clone/images/googleLogo.jpg
  Web Development/Basic/Google Clone/images/sam.jpg
  Web Development/Basic/Google Clone/images/searchIcon.png
  Web Development/Basic/Google Clone/images/voiceIcon.png
  Web Development/Basic/Google Clone/index.html
  Web Development/README.md
Labels: Added Project, hacktoberfest-accepted

#181 BookLibrary project added
  Desktop Application/Basic/Java/BookLibrary/README.md
  Desktop Application/Basic/Java/BookLibrary/ScreenShots/Add book.png
  Desktop Application/Basic/Java/BookLibrary/ScreenShots/Issue book.png
  Desktop Application/Basic/Java/BookLibrary/ScreenShots/Login.png
  Desktop Application/Basic/Java/BookLibrary/ScreenShots/View Stock.png
  Desktop Application/Basic/Java/BookLibrary/build.xml
  Desktop Application/Basic/Java/BookLibrary/build/classes/.netbeans_automatic_build
  Desktop Application/Basic/Java/BookLibrary/build/classes/.netbeans_update_resources
  Desktop Application/Basic/Java/BookLibrary/build/classes/bInterface/BookInterface.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/BookLibrary.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/Call.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/IssueBook.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/IssueStock.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/Login.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/Register.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/ReturnBook.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/ViewStock.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/booklibrary/logout.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/entity/BookEntity.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/entity/Issue.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/entity/LoginEntity.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/impl/Impl.class
  Desktop Application/Basic/Java/BookLibrary/build/classes/util/DbConnection.class
  Desktop Application/Basic/Java/BookLibrary/manifest.mf
  Desktop Application/Basic/Java/BookLibrary/nbproject/build-impl.xml
  Desktop Application/Basic/Java/BookLibrary/nbproject/genfiles.properties
  Desktop Application/Basic/Java/BookLibrary/nbproject/private/private.properties
  Desktop Application/Basic/Java/BookLibrary/nbproject/private/private.xml
  Desktop Application/Basic/Java/BookLibrary/nbproject/project.properties
  Desktop Application/Basic/Java/BookLibrary/nbproject/project.xml
  Desktop Application/Basic/Java/BookLibrary/src/bInterface/BookInterface.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/BookLibrary.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/Call.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/IssueBook.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/IssueStock.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/Login.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/Register.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/ReturnBook.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/ViewStock.java
  Desktop Application/Basic/Java/BookLibrary/src/booklibrary/logout.java
  Desktop Application/Basic/Java/BookLibrary/src/entity/BookEntity.java
  Desktop Application/Basic/Java/BookLibrary/src/entity/Issue.java
  Desktop Application/Basic/Java/BookLibrary/src/entity/LoginEntity.java
  Desktop Application/Basic/Java/BookLibrary/src/impl/Impl.java
  Desktop Application/Basic/Java/BookLibrary/src/util/DbConnection.java
Labels: Added Project

#182 Contact Form
  Web Development/Basic/Contact Form/ContactForm.css
  Web Development/Basic/Contact Form/ContactForm.js
  Web Development/Basic/Contact Form/README.md
  Web Development/Basic/Contact Form/ScreenShot.jpg
  Web Development/Basic/Contact Form/index.html
Labels: Added Project, Updating Project
