Repository Kushal997-das/Project-Guidance, pull requests merged in 2022-04, with the labels that each got.

#455 Add a temperature converter app
  Web Development/Basic/Temperature Converter/README.md
  Web Development/Basic/Temperature Converter/index.html
  Web Development/Basic/Temperature Converter/index.js
  Web Development/Basic/Temperature Converter/script.js
  Web Development/Basic/Temperature Converter/style.css
Labels: Added Project, GSSoC22, Level1

#444 Added Parallex Web Design
  Web Development/Basic/Parallex-Web-Design/Images/demo.png
  Web Development/Basic/Parallex-Web-Design/Images/image1.jpg
  Web Development/Basic/Parallex-Web-Design/Images/image2.jpg
  Web Development/Basic/Parallex-Web-Design/Images/image3.jpg
  Web Development/Basic/Parallex-Web-Design/ParallexEffect.css
  Web Development/Basic/Parallex-Web-Design/ParallexEffect.html
  Web Development/Basic/Parallex-Web-Design/readme.md
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#438 KNN algorithm
  Machine Learning and Data Science/Basic/KNN Algorithm/Confusion Matrix.ipynb
  Machine Learning and Data Science/Basic/KNN Algorithm/KNN algorithm.ipynb
  Machine Learning and Data Science/Basic/KNN Algorithm/Readme.md
Labels: Added Project, GSSoC22, Level1

#456 Updated README.md [Mobile Application]
  Mobile Applications/README.md
Labels: documentation, GSSoC22

#445 Colorful Rain Effect Added
  Web Development/Basic/Colorful Rain Effect/index.html
  Web Development/Basic/Colorful Rain Effect/readme.md
  Web Development/Basic/Colorful Rain Effect/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#460 Word cloud
  Machine Learning and Data Science/Basic/Word-Cloud/Final Project - Word Cloud.ipynb
  Machine Learning and Data Science/Basic/Word-Cloud/Img/README.md
  Machine Learning and Data Science/Basic/Word-Cloud/Img/res.png
  Machine Learning and Data Science/Basic/Word-Cloud/README.md
  Machine Learning and Data Science/Basic/Word-Cloud/test.txt
Labels: Added Project, GSSoC22, Level1

#461 Added teams clone files
  Web Development/Basic/Teams Clone/assets/css/bootstrap.css
  Web Development/Basic/Teams Clone/assets/css/bootstrap.css.map
  Web Development/Basic/Teams Clone/assets/css/style.css
  Web Development/Basic/Teams Clone/assets/media/Teams_Icon.jpg
  Web Development/Basic/Teams Clone/assets/media/person.png
  Web Development/Basic/Teams Clone/index.html
  Web Development/Basic/Teams Clone/readme.md
  Web Development/Basic/Teams Clone/scripts/bootstrap.bundle.js
  Web Development/Basic/Teams Clone/scripts/bootstrap.bundle.js.map
Labels: Added Project, GSSoC22, Level1

#466 Website for non-alcoholic drinks recipes (FruitNotBooze)
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/README.md
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Berry A Peeling.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Coconut Splash.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Cucumber Juice.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Fruity Punch.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Harry potter juice.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Lemon drop.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/Purple Power.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/appleberry lush.jpg
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/eye opener juice.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/fresh salsa.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/green ginger ale.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/heart beet.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/lean green.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/lemon ginger zinger.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/mangolicious citrus.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/midsummer night dream.jpg
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/orange crush.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/pearfection.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/pink panther.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/pink pom.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/pomegranate plus.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/summer breeze.jpg
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/summer melon.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/img/sun kissed.png
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/index.html
  Web Development/Basic/Drinks Recipe Website(FruitNotBooze)/style.css
  Web Development/Basic/Tourist Places/scss/responsive.css
  Web Development/Basic/Tourist Places/scss/responsive.css.map
  Web Development/Basic/Tourist Places/scss/style.css
  Web Development/Basic/Tourist Places/scss/style.css.map
  Web Development/README.md
Labels: Added Project, GSSoC22, Level2

#484 Added Calculator in JAVA under Basic Desktop Applications
  Desktop Application/Basic/Java/Calculator/README.md
  Desktop Application/Basic/Java/Calculator/calculator.gif
  Desktop Application/Basic/Java/Calculator/src/Calculator.java
  Desktop Application/README.md
Labels: Added Project, GSSoC22, Level1

#476 Added claymorphic profile card
  Web Development/Basic/Claymorphic profile card/README.md
  Web Development/Basic/Claymorphic profile card/index.html
  Web Development/Basic/Claymorphic profile card/pic2.jpg
  Web Development/Basic/Claymorphic profile card/style.css
Labels: Added Project, GSSoC22, Level1

#486 White Board
  Web Development/Basic/White Board/README.md
  Web Development/Basic/White Board/css/style.css
  Web Development/Basic/White Board/icons/download.svg
  Web Development/Basic/White Board/icons/eraser.svg
  Web Development/Basic/White Board/icons/pen.svg
  Web Development/Basic/White Board/icons/pic.svg
  Web Development/Basic/White Board/icons/redo.svg
  Web Development/Basic/White Board/icons/sticky.svg
  Web Development/Basic/White Board/icons/undo.svg
  Web Development/Basic/White Board/img/board (1).gif
  Web Development/Basic/White Board/index.html
  Web Development/Basic/White Board/js/script.js
Labels: Added Project, GSSoC22, Level2

#500 Added Arduino Light Sensor Files
  IOT(Internet of Things)/Basic/Arduino_Light_Sensor/Light_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_Light_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Light_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#505 Budget App Added
  Web Development/Basic/Budgeting App/README.md
  Web Development/Basic/Budgeting App/index.html
  Web Development/Basic/Budgeting App/script.js
  Web Development/Basic/Budgeting App/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level2

#509 Added Arduino Serial Monitor files
  IOT(Internet of Things)/Basic/Arduino_Serial_Monitor/Serial_Monitor.ino
  IOT(Internet of Things)/Basic/Arduino_Serial_Monitor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Serial_Monitor/readme.md
Labels: Added Project, GSSoC22, Level1

#514 Added Desktop MP3 Player under Basic Python Desktop Application
  Desktop Application/Basic/Python/Desktop MP3 Player/README.md
  Desktop Application/Basic/Python/Desktop MP3 Player/mp3player.py
  Desktop Application/README.md
Labels: Added Project, GSSoC22, Level1

#508 Added Arduino Color Mix Files
  IOT(Internet of Things)/Basic/Arduino_RGB_Mixing/RGB_Mixing.ino
  IOT(Internet of Things)/Basic/Arduino_RGB_Mixing/Setup.png
  IOT(Internet of Things)/Basic/Arduino_RGB_Mixing/readme.md
Labels: Added Project, GSSoC22, Level1

#506 Simon Game
  Web Development/Basic/Simon Game/README.md
  Web Development/Basic/Simon Game/favicon.png
  Web Development/Basic/Simon Game/game.js
  Web Development/Basic/Simon Game/index.html
  Web Development/Basic/Simon Game/sounds/blue.mp3
  Web Development/Basic/Simon Game/sounds/green.mp3
  Web Development/Basic/Simon Game/sounds/red.mp3
  Web Development/Basic/Simon Game/sounds/wrong.mp3
  Web Development/Basic/Simon Game/sounds/yellow.mp3
  Web Development/Basic/Simon Game/styles.css
Labels: Added Project, GSSoC22, Level1

#515 Added BookStore Management System Files
  Desktop Application/Basic/C/BookStore_Management/Program.c
  Desktop Application/Basic/C/BookStore_Management/readme.md
Labels: Added Project, GSSoC22, Level1

#490 Heart Disease Prediction Completed
  Machine Learning and Data Science/Basic/Heart Disease Prediction/DataSet/heart.csv
  Machine Learning and Data Science/Basic/Heart Disease Prediction/Heart Disease Prediction (Logistic Regression) - Using Library.ipynb
  Machine Learning and Data Science/Basic/Heart Disease Prediction/Heart Disease Prediction (Multiple Linear Regression) - Using Maths.ipynb
  Machine Learning and Data Science/Basic/Heart Disease Prediction/Heart_Disease_using_CNN.ipynb
  Machine Learning and Data Science/Basic/Heart Disease Prediction/README.md
  Machine Learning and Data Science/Basic/Heart Disease Prediction/image/confusionmatrix.png
  Machine Learning and Data Science/Basic/Heart Disease Prediction/image/output-1.png
  Machine Learning and Data Science/Basic/Heart Disease Prediction/image/output.png
  Machine Learning and Data Science/README.md
Labels: Added Project, GSSoC22, Level1

#518 Added To-Do List Project
  Desktop Application/Basic/Python/To-Do List/README.md
  Desktop Application/Basic/Python/To-Do List/Working_ScreenShots/Image.jpeg
  Desktop Application/Basic/Python/To-Do List/main.py
Labels: Added Project, GSSoC22, Level1

#522 Pinterest Static
  Web Development/Basic/pinterest-static/README.md
  Web Development/Basic/pinterest-static/index.html
  Web Development/Basic/pinterest-static/logo.png
  Web Development/Basic/pinterest-static/style.css
  Web Development/Basic/pinterest-static/vu.png
Labels: Added Project, GSSoC22, Level1

#526 Added Arduino Motion Detector files
  IOT(Internet of Things)/Basic/Arduino_PIR_Motion_Sensor/PIR_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_PIR_Motion_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_PIR_Motion_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#527 Added Arduino Temp Sensor files
  IOT(Internet of Things)/Basic/Arduino_Temperature_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Temperature_Sensor/TMP_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_Temperature_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#546 Bug fixes
  Web Development/Basic/pinterest-static/README.md
  Web Development/Basic/pinterest-static/favicon.ico
  Web Development/Basic/pinterest-static/index.css
  Web Development/Basic/pinterest-static/index.html
  Web Development/Basic/pinterest-static/vu.png
Labels: enhancement, Fixed Bug

#523 Added Expense Tracker App
  Web Development/Intermediate/Expense Tracker App/.gitignore
  Web Development/Intermediate/Expense Tracker App/Readme.md
  Web Development/Intermediate/Expense Tracker App/package-lock.json
  Web Development/Intermediate/Expense Tracker App/package.json
  Web Development/Intermediate/Expense Tracker App/public/favicon.ico
  Web Development/Intermediate/Expense Tracker App/public/index.html
  Web Development/Intermediate/Expense Tracker App/public/manifest.json
  Web Development/Intermediate/Expense Tracker App/public/robots.txt
  Web Development/Intermediate/Expense Tracker App/src/App.css
  Web Development/Intermediate/Expense Tracker App/src/App.js
  Web Development/Intermediate/Expense Tracker App/src/components/AddTransactions.js
  Web Development/Intermediate/Expense Tracker App/src/components/Balance.js
  Web Development/Intermediate/Expense Tracker App/src/components/Header.js
  Web Development/Intermediate/Expense Tracker App/src/components/IncomeExpenses.js
  Web Development/Intermediate/Expense Tracker App/src/components/TransactionList.js
  Web Development/Intermediate/Expense Tracker App/src/components/Transactions.js
  Web Development/Intermediate/Expense Tracker App/src/context/AppReducer.js
  Web Development/Intermediate/Expense Tracker App/src/context/GlobalStates.js
  Web Development/Intermediate/Expense Tracker App/src/context/delete.html
  Web Development/Intermediate/Expense Tracker App/src/index.css
  Web Development/Intermediate/Expense Tracker App/src/index.js
  Web Development/Intermediate/Expense Tracker App/src/reportWebVitals.js
  Web Development/Intermediate/Expense Tracker App/src/setupTests.js
Labels: Added Project, GSSoC22, Level1

#524 Desktop basic java
  Desktop Application/Basic/Java/Notepad/Notepad.gif
  Desktop Application/Basic/Java/Notepad/Notepad.iml
  Desktop Application/Basic/Java/Notepad/out/artifacts/Notepad_jar/Notepad.jar
  Desktop Application/Basic/Java/Notepad/out/production/Notepad/META-INF/MANIFEST.MF
  Desktop Application/Basic/Java/Notepad/out/production/Notepad/com/company/About.class
  Desktop Application/Basic/Java/Notepad/out/production/Notepad/com/company/Notepad.class
  Desktop Application/Basic/Java/Notepad/out/production/Notepad/com/company/icons/notepad.png
  Desktop Application/Basic/Java/Notepad/out/production/Notepad/com/company/icons/windows.png
  Desktop Application/Basic/Java/Notepad/readme.md
  Desktop Application/Basic/Java/Notepad/src/META-INF/MANIFEST.MF
  Desktop Application/Basic/Java/Notepad/src/com/company/About.java
  Desktop Application/Basic/Java/Notepad/src/com/company/Notepad.java
  Desktop Application/Basic/Java/Notepad/src/com/company/icons/notepad.png
  Desktop Application/Basic/Java/Notepad/src/com/company/icons/windows.png
Labels: Added Project, GSSoC22, Level2

#530 Online Gaming Portal Template
  Web Development/Intermediate/Online Gaming Portal Template/README.md
  Web Development/Intermediate/Online Gaming Portal Template/assets/Risk.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/Screenshot (183).png
  Web Development/Intermediate/Online Gaming Portal Template/assets/albion.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/anothereden.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/arma3.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/asphalt_re.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/assasinscreed.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/attackontitan.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/batman.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/biomutant.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/bleach.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/bloodsteel.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/borderlands.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/cyberpunk.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/daysgone.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/deadbydaylight3.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/deathstranding.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/divinity2.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/dmc5.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/dyinglight.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/ghostrecon.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/hood.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/icons8-male-user-96.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/icons8-steam-100.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/icons8-twitch-96.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/jumpforce.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/knockoutcity.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/metroexodus.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/neverwinter.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/prev.txt
  Web Development/Intermediate/Online Gaming Portal Template/assets/runescape.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/sekiro.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/shadowofwar.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/skyrim.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/smite.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/snowrunner.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/soccermanager2020.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/soulworker.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/spiderman_re.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/tombraider.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/warframe.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/warhammer2.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/witcher3.png
  Web Development/Intermediate/Online Gaming Portal Template/assets/yugioh.png
  Web Development/Intermediate/Online Gaming Portal Template/index.html
  Web Development/Intermediate/Online Gaming Portal Template/main.css
  Web Development/Intermediate/Online Gaming Portal Template/script.js
Labels: Added Project, GSSoC22, Level2

#540 Centroid digits
  Machine Learning and Data Science/Intermediate/Centroid-Digits/Classify_centriod.ipynb
  Machine Learning and Data Science/Intermediate/Centroid-Digits/README.md
  Machine Learning and Data Science/Intermediate/Centroid-Digits/requirements.txt
Labels: Added Project, GSSoC22, Level1

#537 Handwritten Digit Recognizer Using ANN
  Machine Learning and Data Science/Intermediate/Digit Recognizer Using ANN/README.md
  Machine Learning and Data Science/Intermediate/Digit Recognizer Using ANN/handwritten_digit_classification_using_ann.ipynb
  Machine Learning and Data Science/Intermediate/README.md
Labels: Added Project, GSSoC22, Level1

#542 Added Arduino UltraSonic Sensor files
  IOT(Internet of Things)/Basic/Arduino_UltraSonic_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_UltraSonic_Sensor/UltraSonic_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_UltraSonic_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#529 Command Line Emailer
  Desktop Application/Basic/Python/cmd-line-emailer/emailer.py
  Desktop Application/Basic/Python/cmd-line-emailer/readme.md
Labels: Added Project, GSSoC22, Level1

#545 Added Naruto Website
  Web Development/Intermediate/Naruto/.gitignore
  Web Development/Intermediate/Naruto/Naruto.png
  Web Development/Intermediate/Naruto/package-lock.json
  Web Development/Intermediate/Naruto/package.json
  Web Development/Intermediate/Naruto/public/favicon.ico
  Web Development/Intermediate/Naruto/public/index.html
  Web Development/Intermediate/Naruto/public/logo192.png
  Web Development/Intermediate/Naruto/public/logo512.png
  Web Development/Intermediate/Naruto/public/manifest.json
  Web Development/Intermediate/Naruto/public/robots.txt
  Web Development/Intermediate/Naruto/readme.md
  Web Development/Intermediate/Naruto/src/App.js
  Web Development/Intermediate/Naruto/src/assets/banner1.jpg
  Web Development/Intermediate/Naruto/src/assets/banner4.jpg
  Web Development/Intermediate/Naruto/src/assets/hashirama2.png
  Web Development/Intermediate/Naruto/src/assets/hyuga.png
  Web Development/Intermediate/Naruto/src/assets/itachi2.png
  Web Development/Intermediate/Naruto/src/assets/iwagakure.png
  Web Development/Intermediate/Naruto/src/assets/kirigakure.png
  Web Development/Intermediate/Naruto/src/assets/konohagakure.jpg
  Web Development/Intermediate/Naruto/src/assets/kumogakure.jpg
  Web Development/Intermediate/Naruto/src/assets/logo.png
  Web Development/Intermediate/Naruto/src/assets/madara2.png
  Web Development/Intermediate/Naruto/src/assets/otogakure.png
  Web Development/Intermediate/Naruto/src/assets/senju.png
  Web Development/Intermediate/Naruto/src/assets/sunagakure.png
  Web Development/Intermediate/Naruto/src/assets/uchiha.png
  Web Development/Intermediate/Naruto/src/assets/uzumaki.png
  Web Development/Intermediate/Naruto/src/components/Clans.js
  Web Development/Intermediate/Naruto/src/components/Footer.js
  Web Development/Intermediate/Naruto/src/components/Hero.js
  Web Development/Intermediate/Naruto/src/components/Navbar.js
  Web Development/Intermediate/Naruto/src/components/Shinobi.js
  Web Development/Intermediate/Naruto/src/components/Village.js
  Web Development/Intermediate/Naruto/src/index.css
  Web Development/Intermediate/Naruto/src/index.js
  Web Development/Intermediate/Naruto/yarn.lock
Labels: Added Project, GSSoC22, Level2

#556 Added Arduino LCD files
  IOT(Internet of Things)/Basic/Arduino_LCD_Display/LCD_Display.ino
  IOT(Internet of Things)/Basic/Arduino_LCD_Display/Setup.png
  IOT(Internet of Things)/Basic/Arduino_LCD_Display/readme.md
Labels: Added Project, GSSoC22, Level1

#560 Added Arduino Clone files
  IOT(Internet of Things)/Basic/Arduino_Drone/Drone.ino
  IOT(Internet of Things)/Basic/Arduino_Drone/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Drone/readme.md
Labels: Added Project, GSSoC22, Level1

#563 #499 IPL Prediction completed
  Machine Learning and Data Science/Intermediate/IPL Prediction/DataSet/IPL IMB381IPL2013.csv
  Machine Learning and Data Science/Intermediate/IPL Prediction/MultipleLinearRegression.ipynb
  Machine Learning and Data Science/Intermediate/IPL Prediction/README.md
  Machine Learning and Data Science/Intermediate/IPL Prediction/Regularisation - RIDGE_LASSO_HYBRID.ipynb
Labels: Added Project, GSSoC22, Level2

#539 Adding to-do app using Flask
  Web Development/Intermediate/To-do app/.gitignore
  Web Development/Intermediate/To-do app/README.md
  Web Development/Intermediate/To-do app/__pycache__/app.cpython-38.pyc
  Web Development/Intermediate/To-do app/__pycache__/app2.cpython-38.pyc
  Web Development/Intermediate/To-do app/app.py
  Web Development/Intermediate/To-do app/requirements.txt
  Web Development/Intermediate/To-do app/screenshots/Home.PNG
  Web Development/Intermediate/To-do app/screenshots/Login.PNG
  Web Development/Intermediate/To-do app/screenshots/Register.PNG
  Web Development/Intermediate/To-do app/screenshots/Thumbs.db
  Web Development/Intermediate/To-do app/screenshots/add-new-task.png
  Web Development/Intermediate/To-do app/screenshots/completed-tasks.png
  Web Development/Intermediate/To-do app/screenshots/edit-completed-task.png
  Web Development/Intermediate/To-do app/screenshots/edit-uncompleted-task.png
  Web Development/Intermediate/To-do app/screenshots/uncompleted-tasks.png
  Web Development/Intermediate/To-do app/static/styles.css
  Web Development/Intermediate/To-do app/templates/base.html
  Web Development/Intermediate/To-do app/templates/header.html
  Web Development/Intermediate/To-do app/templates/index.html
  Web Development/Intermediate/To-do app/templates/login.html
  Web Development/Intermediate/To-do app/templates/not_found.html
  Web Development/Intermediate/To-do app/templates/register.html
  Web Development/Intermediate/To-do app/templates/todo.html
  Web Development/Intermediate/To-do app/templates/todo_form.html
  Web Development/Intermediate/To-do app/todos_db
Labels: Added Project, GSSoC22, Level2

#572 Atm machine
  Desktop Application/Basic/Python/ATM/atm.py
  Desktop Application/Basic/Python/ATM/readme.md
Labels: Added Project, GSSoC22, Level1

#564 Type Writer Effect Project Added
  Web Development/Basic/Type Writer Effect/README.md
  Web Development/Basic/Type Writer Effect/css/style.css
  Web Development/Basic/Type Writer Effect/images/img.png
  Web Development/Basic/Type Writer Effect/index.html
  Web Development/Basic/Type Writer Effect/js/index.js
Labels: Added Project, GSSoC22, Level1

#566 Quote Generator
  Web Development/Basic/Quote Generator/README.md
  Web Development/Basic/Quote Generator/app.js
  Web Development/Basic/Quote Generator/favicon.png
  Web Development/Basic/Quote Generator/images/dark_close.png
  Web Development/Basic/Quote Generator/images/dark_open.png
  Web Development/Basic/Quote Generator/index.html
  Web Development/Basic/Quote Generator/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#568 Admission Prediction Using Machine Learning
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/Admission Prediction .ipynb
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/Admission_Prediction.csv
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/Readme.md
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/finalized_model.pickle
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/images/L1.PNG
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/images/MLApplicationFlow_bold.png
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/images/RSS_reg.PNG
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/images/elasticNet.PNG
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/images/ridge.PNG
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/images/ridge_vs_lasso.PNG
  Machine Learning and Data Science/Basic/Admission Prediction Using Linear Regression/requirements.txt
Labels: Added Project, GSSoC22, Level1
