Repository Kushal997-das/Project-Guidance, pull requests merged in 2022-05, with the labels that each got.

#581 Added notes app
  Web Development/Basic/Notes Taking App/Readme.md
  Web Development/Basic/Notes Taking App/index.html
  Web Development/Basic/Notes Taking App/script.js
  Web Development/Basic/Notes Taking App/style.css
Labels: Added Project, GSSoC22, Level1

#574 Added Arduino_IR_Sensor files
  IOT(Internet of Things)/Basic/Arduino_IR_Sensor/IR_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_IR_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_IR_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#573 Added Arduino_Servo_Motor files
  IOT(Internet of Things)/Basic/Arduino_Servo_Motor/Servo.ino
  IOT(Internet of Things)/Basic/Arduino_Servo_Motor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Servo_Motor/readme.md
Labels: Added Project, GSSoC22, Level1

#588 Blurry Loading
  Web Development/Basic/blurry_loading/README.md
  Web Development/Basic/blurry_loading/index.html
  Web Development/Basic/blurry_loading/script.js
  Web Development/Basic/blurry_loading/style.css
Labels: Added Project, GSSoC22, Level1

#590 Added Arduino_Moisture_Sensor files
  IOT(Internet of Things)/Basic/Arduino_Moisture_Sensor/Moisture_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_Moisture_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Moisture_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#597 Added Arduino_Inclination_Sensor files
  IOT(Internet of Things)/Basic/Arduino_Inclination_Sensor/Inclination_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_Inclination_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Inclination_Sensor/readme.md
Labels: Added Project, GSSoC22, Level1

#603 Added Stock Market Project
  Web Development/Intermediate/Stock Market/.gitignore
  Web Development/Intermediate/Stock Market/1.png
  Web Development/Intermediate/Stock Market/2.png
  Web Development/Intermediate/Stock Market/3.png
  Web Development/Intermediate/Stock Market/index.js
  Web Development/Intermediate/Stock Market/package-lock.json
  Web Development/Intermediate/Stock Market/package.json
  Web Development/Intermediate/Stock Market/readme.md
  Web Development/Intermediate/Stock Market/views/about.handlebars
  Web Development/Intermediate/Stock Market/views/home.handlebars
  Web Development/Intermediate/Stock Market/views/layouts/main.handlebars
Labels: Added Project, GSSoC22, Level2

#602 Added Hospital management system
  Web Development/Advanced/hospital management system/Readme.md
  Web Development/Advanced/hospital management system/appointment.php
  Web Development/Advanced/hospital management system/contact.php
  Web Development/Advanced/hospital management system/counselling.php
  Web Development/Advanced/hospital management system/db.php
  Web Development/Advanced/hospital management system/details.php
  Web Development/Advanced/hospital management system/fetch.php
  Web Development/Advanced/hospital management system/filters.php
  Web Development/Advanced/hospital management system/home.php
  Web Development/Advanced/hospital management system/home1.php
  Web Development/Advanced/hospital management system/images/backpain.jpg
  Web Development/Advanced/hospital management system/images/doctor.avif
  Web Development/Advanced/hospital management system/images/doctor.jpg
  Web Development/Advanced/hospital management system/images/doctor.png
  Web Development/Advanced/hospital management system/images/headache.jpg
  Web Development/Advanced/hospital management system/images/kneepain.jpg
  Web Development/Advanced/hospital management system/images/logo.png
  Web Development/Advanced/hospital management system/images/profile.png
  Web Development/Advanced/hospital management system/images/skininfection.jpg
  Web Development/Advanced/hospital management system/images/stomach.jpg
  Web Development/Advanced/hospital management system/images/thyroid.jpg
  Web Development/Advanced/hospital management system/images/thyroid.png
  Web Development/Advanced/hospital management system/in.php
  Web Development/Advanced/hospital management system/institution.php
  Web Development/Advanced/hospital management system/login.php
  Web Development/Advanced/hospital management system/logout.php
  Web Development/Advanced/hospital management system/nav.php
  Web Development/Advanced/hospital management system/navbar.php
  Web Development/Advanced/hospital management system/profile.php
  Web Development/Advanced/hospital management system/query.php
  Web Development/Advanced/hospital management system/register.php
  Web Development/Advanced/hospital management system/search.php
  Web Development/Advanced/hospital management system/services.php
  Web Development/Advanced/hospital management system/style.css
  Web Development/Advanced/hospital management system/t.php
  Web Development/Advanced/hospital management system/updateprofile.php
  Web Development/Advanced/hospital management system/yourappoint.php
Labels: Under-review, GSSoC22, Level2

#605 E-Commerce Fashion Website
  Web Development/Advanced/E-Commerce Website/about.html
  Web Development/Advanced/E-Commerce Website/about.jfif
  Web Development/Advanced/E-Commerce Website/avatar1.jfif
  Web Development/Advanced/E-Commerce Website/avatar2.jfif
  Web Development/Advanced/E-Commerce Website/avatar3.jfif
  Web Development/Advanced/E-Commerce Website/cart.html
  Web Development/Advanced/E-Commerce Website/cart2
  Web Development/Advanced/E-Commerce Website/cart3.jfif
  Web Development/Advanced/E-Commerce Website/cat1.jfif
  Web Development/Advanced/E-Commerce Website/catagory.html
  Web Development/Advanced/E-Commerce Website/checkout.html
  Web Development/Advanced/E-Commerce Website/contact.html
  Web Development/Advanced/E-Commerce Website/index.html
  Web Development/Advanced/E-Commerce Website/logo.jpg
  Web Development/Advanced/E-Commerce Website/order_confirm.png
  Web Development/Advanced/E-Commerce Website/order_confirmation.html
  Web Development/Advanced/E-Commerce Website/product.html
  Web Development/Advanced/E-Commerce Website/product1.jfif
  Web Development/Advanced/E-Commerce Website/product2.jfif
  Web Development/Advanced/E-Commerce Website/product3.jfif
  Web Development/Advanced/E-Commerce Website/product4.jfif
  Web Development/Advanced/E-Commerce Website/product6.jfif
  Web Development/Advanced/E-Commerce Website/product_detail.html
  Web Development/Advanced/E-Commerce Website/readme.md
  Web Development/Advanced/E-Commerce Website/search.html
  Web Development/Advanced/E-Commerce Website/slide1.jpg
  Web Development/Advanced/E-Commerce Website/slide2.png
  Web Development/Advanced/E-Commerce Website/slide3.png
  Web Development/Advanced/E-Commerce Website/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level2

#619 Added technical documentation page
  Web Development/Basic/Technical_Documentation_Page/README.md
  Web Development/Basic/Technical_Documentation_Page/index.html
  Web Development/Basic/Technical_Documentation_Page/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#620 WhatsApp Chat Analyzer -Data Analysis
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/Readme.md
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/__pycache__/app.cpython-37.pyc
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/__pycache__/helper.cpython-37.pyc
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/__pycache__/preprocessor.cpython-37.pyc
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/app.py
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/helper.py
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/img_1.png
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/preprocessor.py
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/requirements.txt
  Machine Learning and Data Science/Intermediate/Whatsapp Chat Analyzer/stopwords.txt
Labels: Added Project, GSSoC22, Level2

#621 Age Calculator
  Desktop Application/Basic/Python/Age calculator/README.md
  Desktop Application/Basic/Python/Age calculator/age.py
  Desktop Application/Basic/Python/Age calculator/img/Screenshot 2022-05-04 131349.png
Labels: Added Project, GSSoC22, Level0

#628 Burger Eye
  Web Development/Basic/Burger Eye/README.md
  Web Development/Basic/Burger Eye/burger.png
  Web Development/Basic/Burger Eye/favicon.png
  Web Development/Basic/Burger Eye/index.html
  Web Development/Basic/Burger Eye/index.js
  Web Development/Basic/Burger Eye/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#631 Quiz App - Mobile Application
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/project.pbxproj
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/project.xcworkspace/xcuserdata/abhishek.xcuserdatad/UserInterfaceState.xcuserstate
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/project.xcworkspace/xcuserdata/angelayu.xcuserdatad/UserInterfaceState.xcuserstate
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/xcuserdata/abhishek.xcuserdatad/xcschemes/xcschememanagement.plist
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13.xcodeproj/xcuserdata/angelayu.xcuserdatad/xcschemes/xcschememanagement.plist
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/AppDelegate.swift
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/100.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/1024.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/114.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/120.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/144.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/152.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/167.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/180.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/20.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/29.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/40.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/50.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/57.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/58.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/60.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/72.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/76.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/80.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/87.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/AppIcon.appiconset/Contents.json
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Background-Bubbles.imageset/Background-Bubbles.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Background-Bubbles.imageset/Background-Bubbles@2x.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Background-Bubbles.imageset/Background-Bubbles@3x.png
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Background-Bubbles.imageset/Contents.json
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Contents.json
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Rectangle.imageset/Contents.json
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Assets.xcassets/Rectangle.imageset/Rectangle.pdf
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Base.lproj/LaunchScreen.storyboard
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Controller/ViewController.swift
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Info.plist
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Model/Question.swift
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/Model/QuizBrain.swift
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/SceneDelegate.swift
  Mobile Applications/Intermediate/Quizzing App/Quizzler-iOS13/Quizzler-iOS13/View/Base.lproj/Main.storyboard
  Mobile Applications/Intermediate/Quizzing App/README.md
Labels: Added Project, GSSoC22, Level2

#635 Added ArduinoGasSensor files
  IOT(Internet of Things)/Basic/Arduino_Gas_Sensor/Gas_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_Gas_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Gas_Sensor/readme.md
Labels: Added Project, GSSoC22, Level0

#636 Added ArduinoStressSensor files
  IOT(Internet of Things)/Basic/Arduino_Stress_Sensor/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Stress_Sensor/Stress_Sensor.ino
  IOT(Internet of Things)/Basic/Arduino_Stress_Sensor/readme.md
Labels: Added Project, GSSoC22, Level0

#639 Added restaurant systems GUI
  Desktop Application/Basic/Python/Restaurant Management Systems/Readme.md
  Desktop Application/Basic/Python/Restaurant Management Systems/Restaurant_Management_Systems.py
Labels: Added Project, GSSoC22, Level1

#640 Internet Speed Meter using Python
  Desktop Application/Basic/Python/Internet Speed Meter/README.md
  Desktop Application/Basic/Python/Internet Speed Meter/internet.py
Labels: Added Project, GSSoC22, Level1

#623 Title: Medical Data Visualizer
  Machine Learning and Data Science/Basic/Medical Data Visualizer/README.md
  Machine Learning and Data Science/Basic/Medical Data Visualizer/catplot.png
  Machine Learning and Data Science/Basic/Medical Data Visualizer/heatmap.png
  Machine Learning and Data Science/Basic/Medical Data Visualizer/main.py
  Machine Learning and Data Science/Basic/Medical Data Visualizer/medical_data_visualizer.py
  Machine Learning and Data Science/Basic/Medical Data Visualizer/medical_examination.csv
  Machine Learning and Data Science/Basic/Medical Data Visualizer/test_module.py
Labels: Added Project, GSSoC22, Level1

#651 Meme-Generator
  Web Development/Basic/Meme-Generator/README.md
  Web Development/Basic/Meme-Generator/index.html
  Web Development/Basic/Meme-Generator/script.js
  Web Development/Basic/Meme-Generator/style.css
Labels: Added Project, GSSoC22, Level1

#652 Arduino Crocodile Dentist - IOT
  IOT(Internet of Things)/Basic/Arduino_Crocodile_Dentist/Code.ino
  IOT(Internet of Things)/Basic/Arduino_Crocodile_Dentist/Design File.brd
  IOT(Internet of Things)/Basic/Arduino_Crocodile_Dentist/README.md
  IOT(Internet of Things)/Basic/Arduino_Crocodile_Dentist/Setup.png
Labels: Added Project, GSSoC22, Level1

#648 Added text to speech application
  Mobile Applications/Intermediate/TextToSpeechApplication/.gitignore
  Mobile Applications/Intermediate/TextToSpeechApplication/Readme.md
  Mobile Applications/Intermediate/TextToSpeechApplication/app/.gitignore
  Mobile Applications/Intermediate/TextToSpeechApplication/app/build.gradle
  Mobile Applications/Intermediate/TextToSpeechApplication/app/proguard-rules.pro
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/androidTest/java/com/example/texttospeechapplication/ExampleInstrumentedTest.java
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/AndroidManifest.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/java/com/example/texttospeechapplication/MainActivity.java
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/drawable/ic_launcher_background.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/layout/activity_main.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/values-night/themes.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/values/colors.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/values/strings.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/main/res/values/themes.xml
  Mobile Applications/Intermediate/TextToSpeechApplication/app/src/test/java/com/example/texttospeechapplication/ExampleUnitTest.java
  Mobile Applications/Intermediate/TextToSpeechApplication/build.gradle
  Mobile Applications/Intermediate/TextToSpeechApplication/gradle.properties
  Mobile Applications/Intermediate/TextToSpeechApplication/gradle/wrapper/gradle-wrapper.jar
  Mobile Applications/Intermediate/TextToSpeechApplication/gradle/wrapper/gradle-wrapper.properties
  Mobile Applications/Intermediate/TextToSpeechApplication/gradlew
  Mobile Applications/Intermediate/TextToSpeechApplication/gradlew.bat
  Mobile Applications/Intermediate/TextToSpeechApplication/settings.gradle
Labels: Added Project, GSSoC22, Level2

#661 Added Temperature Converter Tool
  Desktop Application/Basic/Java/Temperature Convertor Tool/Main.iml
  Desktop Application/Basic/Java/Temperature Convertor Tool/TCT.gif
  Desktop Application/Basic/Java/Temperature Convertor Tool/Temperature Convertor Tool.iml
  Desktop Application/Basic/Java/Temperature Convertor Tool/out/artifacts/Main_jar/Main.jar
  Desktop Application/Basic/Java/Temperature Convertor Tool/pom.xml
  Desktop Application/Basic/Java/Temperature Convertor Tool/readme.md
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/java/META-INF/MANIFEST.MF
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/java/com/example/main/HelloApplication.java
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/java/com/example/main/HelloController.java
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/java/com/example/main/temperature_convertor_tool/HelloApplication.java
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/java/com/example/main/temperature_convertor_tool/HelloController.java
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/java/module-info.java
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/resources/com/example/main/hello-view.fxml
  Desktop Application/Basic/Java/Temperature Convertor Tool/src/main/resources/com/example/main/temperature_convertor_tool/hello-view.fxml
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/com/example/main/HelloApplication.class
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/com/example/main/HelloController.class
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/com/example/main/hello-view.fxml
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/com/example/main/temperature_convertor_tool/HelloApplication.class
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/com/example/main/temperature_convertor_tool/HelloController.class
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/com/example/main/temperature_convertor_tool/hello-view.fxml
  Desktop Application/Basic/Java/Temperature Convertor Tool/target/classes/module-info.class
Labels: Added Project, GSSoC22, Level2

#684 Added Arduino_Car_Game files
  IOT(Internet of Things)/Basic/Arduino_Car_Game/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Car_Game/game.ino
  IOT(Internet of Things)/Basic/Arduino_Car_Game/readme.md
Labels: Added Project, GSSoC22, Level0

#685 Added Arduino_Logic_IC_Tester files
  IOT(Internet of Things)/Basic/Arduino_Logic_IC_Tester/Logic_IC_Tester.ino
  IOT(Internet of Things)/Basic/Arduino_Logic_IC_Tester/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Logic_IC_Tester/readme.md
Labels: Added Project, GSSoC22, Level1

#644 Emotion + Pose detection completed
  Artificial Intelligence/Basic/Emotion + Posture Detection/EmotionAndPosture.py
  Artificial Intelligence/Basic/Emotion + Posture Detection/IMG/Screenshot 2022-05-10 at 6.50.07 PM.png
  Artificial Intelligence/Basic/Emotion + Posture Detection/README.md
Labels: Added Project, GSSoC22, Level1

#665 Anime
  Web Development/Intermediate/Anime/README.md
  Web Development/Intermediate/Anime/anime2.css
  Web Development/Intermediate/Anime/anime2.html
  Web Development/Intermediate/Anime/images/aot.jpg
  Web Development/Intermediate/Anime/images/codegeass.jpg
  Web Development/Intermediate/Anime/images/deathnote.jpg
  Web Development/Intermediate/Anime/images/demon.jpg
  Web Development/Intermediate/Anime/images/detectiveconan.jpg
  Web Development/Intermediate/Anime/images/download (1).jpg
  Web Development/Intermediate/Anime/images/download (2).jpg
  Web Development/Intermediate/Anime/images/download (3).jpg
  Web Development/Intermediate/Anime/images/download (4).jpg
  Web Development/Intermediate/Anime/images/download.jpg
  Web Development/Intermediate/Anime/images/monster.jpg
  Web Development/Intermediate/Anime/images/silent.jpg
  Web Development/Intermediate/Anime/images/weathering.jpg
  Web Development/Intermediate/Anime/images/yourname.jpg
  Web Development/Intermediate/Anime/images/yournameng.jpg
  Web Development/Intermediate/Anime/movies.html
  Web Development/Intermediate/Anime/mystery.html
Labels: Added Project, GSSoC22, Level2

#666 Space War Game
  Desktop Application/Intermediate/Python/Space War/README.md
  Desktop Application/Intermediate/Python/Space War/img/meteorBrown_med1.png
  Desktop Application/Intermediate/Python/Space War/img/playerShip1_orange.png
  Desktop Application/Intermediate/Python/Space War/img/space.png
  Desktop Application/Intermediate/Python/Space War/img/space_open_space_planets_135213_360x640.jpg
  Desktop Application/Intermediate/Python/Space War/start.py
Labels: Added Project, GSSoC22, Level1

#674 Added clipboard application
  Mobile Applications/Intermediate/clipBoardApp/.gitignore
  Mobile Applications/Intermediate/clipBoardApp/Readme.md
  Mobile Applications/Intermediate/clipBoardApp/app/.gitignore
  Mobile Applications/Intermediate/clipBoardApp/app/build.gradle
  Mobile Applications/Intermediate/clipBoardApp/app/proguard-rules.pro
  Mobile Applications/Intermediate/clipBoardApp/app/src/androidTest/java/com/example/clipboardapp/ExampleInstrumentedTest.java
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/AndroidManifest.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/java/com/example/clipboardapp/MainActivity.java
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/drawable/ic_launcher_background.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/drawable/rec.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/layout/activity_main.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/values-night/themes.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/values/colors.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/values/strings.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/main/res/values/themes.xml
  Mobile Applications/Intermediate/clipBoardApp/app/src/test/java/com/example/clipboardapp/ExampleUnitTest.java
  Mobile Applications/Intermediate/clipBoardApp/build.gradle
  Mobile Applications/Intermediate/clipBoardApp/gradle.properties
  Mobile Applications/Intermediate/clipBoardApp/gradle/wrapper/gradle-wrapper.jar
  Mobile Applications/Intermediate/clipBoardApp/gradle/wrapper/gradle-wrapper.properties
  Mobile Applications/Intermediate/clipBoardApp/gradlew
  Mobile Applications/Intermediate/clipBoardApp/gradlew.bat
  Mobile Applications/Intermediate/clipBoardApp/settings.gradle
Labels: Added Project, GSSoC22, Level2

#676 Added live news app
  Desktop Application/Basic/Python/Live News App/Live_News.py
  Desktop Application/Basic/Python/Live News App/Readme.md
Labels: Added Project, GSSoC22, Level0

#677 Multi Arduino Knight rider lights
  IOT(Internet of Things)/Basic/Multi Arduino Knight Rider Lights/Code.ino
  IOT(Internet of Things)/Basic/Multi Arduino Knight Rider Lights/Design.brd
  IOT(Internet of Things)/Basic/Multi Arduino Knight Rider Lights/README.md
  IOT(Internet of Things)/Basic/Multi Arduino Knight Rider Lights/Setup.png
Labels: Added Project, GSSoC22, Level0

#662 Block Mario Game (done Chenges)
  Web Development/Basic/Block Retro Mario Game/index.html
  Web Development/Basic/Block Retro Mario Game/readme.md
  Web Development/Basic/Block Retro Mario Game/script.js
  Web Development/Basic/Block Retro Mario Game/style.css
Labels: Added Project, GSSoC22, Level1

#669 Added Random Joke Generator added. Web Development
  Web Development/Basic/Random Joke Generator/README.md
  Web Development/Basic/Random Joke Generator/index.html
  Web Development/Basic/Random Joke Generator/script.js
  Web Development/Basic/Random Joke Generator/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#691 Python GUI Calendar Application
  Desktop Application/Basic/Python/GUI Calendar/README.md
  Desktop Application/Basic/Python/GUI Calendar/calendar.py
  Desktop Application/README.md
Labels: Added Project, GSSoC22, Level1

#690 Added Trimorphic Number Checker
  Web Development/Basic/Trimorphic Number Checker/Readme.md
  Web Development/Basic/Trimorphic Number Checker/index.html
  Web Development/Basic/Trimorphic Number Checker/script/script.js
  Web Development/Basic/Trimorphic Number Checker/snips/snip.png
  Web Development/Basic/Trimorphic Number Checker/style/style.css
Labels: Added Project, GSSoC22, Level1

#693 Title: Page View Time Series Visualizer
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/README.md
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/img/bar_plot.png
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/img/box_plot.png
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/img/line_plot.png
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/main.py
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/pageviews.csv
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/test_module.py
  Machine Learning and Data Science/Basic/Page View Time Series Visualizer/time_series_visualizer.py
Labels: Added Project, GSSoC22, Level1

#668 Esports Website
  Web Development/Intermediate/Esports Website/Images/aov.jpg
  Web Development/Intermediate/Esports Website/Images/cod.jpg
  Web Development/Intermediate/Esports Website/Images/ff.jpeg
  Web Development/Intermediate/Esports Website/Images/i1.jpg
  Web Development/Intermediate/Esports Website/Images/i2.jpg
  Web Development/Intermediate/Esports Website/Images/league.jpg
  Web Development/Intermediate/Esports Website/app.css
  Web Development/Intermediate/Esports Website/index.html
  Web Development/Intermediate/Esports Website/readme.md
Labels: Added Project, GSSoC22, Level1

#671 Railway (done Changes)
  Desktop Application/Basic/C/Railway Management System/booklist.txt
  Desktop Application/Basic/C/Railway Management System/booklistreport.txt
  Desktop Application/Basic/C/Railway Management System/railwaymanagementsystem.cpp
  Desktop Application/Basic/C/Railway Management System/railwaymanagementsystem.exe
  Desktop Application/Basic/C/Railway Management System/readme.md
  Desktop Application/Basic/C/Railway Management System/train_details.txt
  Desktop Application/Basic/C/Railway Management System/train_report.txt
Labels: Added Project, GSSoC22, Level1

#695 Added Arduino_TrafficLight_Simulator files
  IOT(Internet of Things)/Basic/Arduino_TrafficLight_Simulator/Setup.png
  IOT(Internet of Things)/Basic/Arduino_TrafficLight_Simulator/TrafficLight_Simulator.ino
  IOT(Internet of Things)/Basic/Arduino_TrafficLight_Simulator/readme.md
Labels: Added Project, GSSoC22, Level1

#699 Chat Application using socket.io
  Web Development/Intermediate/ChatApp/README.md
  Web Development/Intermediate/ChatApp/package-lock.json
  Web Development/Intermediate/ChatApp/package.json
  Web Development/Intermediate/ChatApp/public/chat.html
  Web Development/Intermediate/ChatApp/public/css/style.css
  Web Development/Intermediate/ChatApp/public/index.html
  Web Development/Intermediate/ChatApp/public/js/main.js
  Web Development/Intermediate/ChatApp/server.js
  Web Development/Intermediate/ChatApp/utils/messages.js
  Web Development/Intermediate/ChatApp/utils/users.js
  Web Development/README.md
Labels: Added Project, GSSoC22, Level2

#708 Registration
  Desktop Application/Basic/Java/RegistrationForm/Main.java
  Desktop Application/Basic/Java/RegistrationForm/RegistrationForm.java
  Desktop Application/Basic/Java/RegistrationForm/readme.md
Labels: Added Project, GSSoC22, Level1

#710 Library
  Desktop Application/Basic/Java/Library Management System/Library.java
  Desktop Application/Basic/Java/Library Management System/book.java
  Desktop Application/Basic/Java/Library Management System/books.java
  Desktop Application/Basic/Java/Library Management System/readme.md
  Desktop Application/Basic/Java/Library Management System/student.java
  Desktop Application/Basic/Java/Library Management System/students.java
Labels: Added Project, GSSoC22, Level0

#711 Added Perfect Number Checker
  Web Development/Basic/Perfect Number Checker/Readme.md
  Web Development/Basic/Perfect Number Checker/index.html
  Web Development/Basic/Perfect Number Checker/script/script.js
  Web Development/Basic/Perfect Number Checker/snips/snip1.png
  Web Development/Basic/Perfect Number Checker/style/style.css
Labels: Added Project, GSSoC22, Level1

#716 Title: Sea Level Predictor
  Machine Learning and Data Science/Basic/Sea Level Predictor/README.md
  Machine Learning and Data Science/Basic/Sea Level Predictor/epa-sea-level.csv
  Machine Learning and Data Science/Basic/Sea Level Predictor/main.py
  Machine Learning and Data Science/Basic/Sea Level Predictor/sea_level_plot.png
  Machine Learning and Data Science/Basic/Sea Level Predictor/sea_level_predictor.py
  Machine Learning and Data Science/Basic/Sea Level Predictor/test_module.py
Labels: Added Project, GSSoC22, Level1

#723 Reach To the End (changes done)
  Web Development/Basic/Reach To The End Game/index.html
  Web Development/Basic/Reach To The End Game/readme.md
  Web Development/Basic/Reach To The End Game/script.js
  Web Development/Basic/Reach To The End Game/style.css
Labels: Added Project, GSSoC22, Level1

#733 Atom
  Web Development/Basic/Atom animated/README.md
  Web Development/Basic/Atom animated/index.html
  Web Development/Basic/Atom animated/style.css
Labels: Added Project, GSSoC22, Level1

#725 Blinking Memory Game
  Web Development/Basic/Blinking Game/index.html
  Web Development/Basic/Blinking Game/preview.gif
  Web Development/Basic/Blinking Game/readme.md
  Web Development/Basic/Blinking Game/script.js
  Web Development/Basic/Blinking Game/style.css
Labels: Added Project, GSSoC22, Level1

#727 Slidegame
  Web Development/Basic/Slide And Collect Game/index.html
  Web Development/Basic/Slide And Collect Game/readme.md
  Web Development/Basic/Slide And Collect Game/script.js
  Web Development/Basic/Slide And Collect Game/style.css
Labels: Added Project, GSSoC22, Level1

#732 Voice app
  Mobile Applications/Basic/Voicetotext/.gitignore
  Mobile Applications/Basic/Voicetotext/.idea/.gitignore
  Mobile Applications/Basic/Voicetotext/.idea/compiler.xml
  Mobile Applications/Basic/Voicetotext/.idea/deploymentTargetDropDown.xml
  Mobile Applications/Basic/Voicetotext/.idea/gradle.xml
  Mobile Applications/Basic/Voicetotext/.idea/misc.xml
  Mobile Applications/Basic/Voicetotext/README.md
  Mobile Applications/Basic/Voicetotext/app/.gitignore
  Mobile Applications/Basic/Voicetotext/app/build.gradle
  Mobile Applications/Basic/Voicetotext/app/proguard-rules.pro
  Mobile Applications/Basic/Voicetotext/app/src/androidTest/java/com/example/voicetotext/ExampleInstrumentedTest.kt
  Mobile Applications/Basic/Voicetotext/app/src/main/AndroidManifest.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/java/com/example/voicetotext/MainActivity.kt
  Mobile Applications/Basic/Voicetotext/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/drawable/ic_launcher_background.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/font/andada.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/layout/activity_main.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Mobile Applications/Basic/Voicetotext/app/src/main/res/values-night/themes.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/values/colors.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/values/font_certs.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/values/preloaded_fonts.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/values/strings.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/values/themes.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/xml/backup_rules.xml
  Mobile Applications/Basic/Voicetotext/app/src/main/res/xml/data_extraction_rules.xml
  Mobile Applications/Basic/Voicetotext/app/src/test/java/com/example/voicetotext/ExampleUnitTest.kt
  Mobile Applications/Basic/Voicetotext/build.gradle
  Mobile Applications/Basic/Voicetotext/gradle.properties
  Mobile Applications/Basic/Voicetotext/gradle/wrapper/gradle-wrapper.jar
  Mobile Applications/Basic/Voicetotext/gradle/wrapper/gradle-wrapper.properties
  Mobile Applications/Basic/Voicetotext/gradlew
  Mobile Applications/Basic/Voicetotext/gradlew.bat
  Mobile Applications/Basic/Voicetotext/settings.gradle
  Mobile Applications/README.md
Labels: Added Project, GSSoC22, Level2

#734 Added rock, paper, scissors game
  Web Development/Basic/RockPaperScissors/README.md
  Web Development/Basic/RockPaperScissors/app.js
  Web Development/Basic/RockPaperScissors/index.html
  Web Development/Basic/RockPaperScissors/style.css
Labels: Added Project, GSSoC22, Level1

#737 Advanced Authentication system added
  Web Development/Advanced/Authentication System/README.md
  Web Development/Advanced/Authentication System/client/package-lock.json
  Web Development/Advanced/Authentication System/client/package.json
  Web Development/Advanced/Authentication System/client/public/favicon.ico
  Web Development/Advanced/Authentication System/client/public/index.html
  Web Development/Advanced/Authentication System/client/src/App.js
  Web Development/Advanced/Authentication System/client/src/components/Navbar.css
  Web Development/Advanced/Authentication System/client/src/components/Navbar.jsx
  Web Development/Advanced/Authentication System/client/src/components/Screens/Email.module.css
  Web Development/Advanced/Authentication System/client/src/components/Screens/EmailVerify.jsx
  Web Development/Advanced/Authentication System/client/src/components/Screens/Login.module.css
  Web Development/Advanced/Authentication System/client/src/components/Screens/LoginScreen.jsx
  Web Development/Advanced/Authentication System/client/src/components/Screens/PrivateScreen.css
  Web Development/Advanced/Authentication System/client/src/components/Screens/PrivateScreen.jsx
  Web Development/Advanced/Authentication System/client/src/components/Screens/Profile.jsx
  Web Development/Advanced/Authentication System/client/src/components/Screens/RegisterScreen.jsx
  Web Development/Advanced/Authentication System/client/src/components/Screens/RegisterScreen.module.css
  Web Development/Advanced/Authentication System/client/src/components/routing/PrivateRoute.js
  Web Development/Advanced/Authentication System/client/src/images/success.png
  Web Development/Advanced/Authentication System/client/src/index.css
  Web Development/Advanced/Authentication System/client/src/index.js
  Web Development/Advanced/Authentication System/client/src/reportWebVitals.js
  Web Development/Advanced/Authentication System/config/db.js
  Web Development/Advanced/Authentication System/controllers/auth.js
  Web Development/Advanced/Authentication System/controllers/user.js
  Web Development/Advanced/Authentication System/middleware/auth.js
  Web Development/Advanced/Authentication System/middleware/error.js
  Web Development/Advanced/Authentication System/models/User.js
  Web Development/Advanced/Authentication System/models/verifyMailToken.js
  Web Development/Advanced/Authentication System/package-lock.json
  Web Development/Advanced/Authentication System/package.json
  Web Development/Advanced/Authentication System/routes/auth.js
  Web Development/Advanced/Authentication System/routes/user.js
  Web Development/Advanced/Authentication System/server.js
  Web Development/Advanced/Authentication System/utils/errorResponse.js
  Web Development/Advanced/Authentication System/utils/sendEmail.js
  Web Development/Advanced/README.md
Labels: Added Project, GSSoC22, Level2
