Repository Kushal997-das/Project-Guidance, pull requests merged in 2022-03, with the labels that each got.

#213 Testing
  README.md
Labels: documentation

#200 Added Spotify Landing Page Clone
  Web Development/Basic/Spotify Landing Page Clone/README.md
  Web Development/Basic/Spotify Landing Page Clone/index.html
  Web Development/Basic/Spotify Landing Page Clone/launch.json
  Web Development/Basic/Spotify Landing Page Clone/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#225 Add Drum Kit Project to Basic Web Development Folder
  Web Development/Basic/Drum Kit/Readme.md
  Web Development/Basic/Drum Kit/images/crash.png
  Web Development/Basic/Drum Kit/images/kick.png
  Web Development/Basic/Drum Kit/images/snare.png
  Web Development/Basic/Drum Kit/images/tom1.png
  Web Development/Basic/Drum Kit/images/tom2.png
  Web Development/Basic/Drum Kit/images/tom3.png
  Web Development/Basic/Drum Kit/images/tom4.png
  Web Development/Basic/Drum Kit/index.html
  Web Development/Basic/Drum Kit/index.js
  Web Development/Basic/Drum Kit/sounds/crash.mp3
  Web Development/Basic/Drum Kit/sounds/kick-bass.mp3
  Web Development/Basic/Drum Kit/sounds/snare.mp3
  Web Development/Basic/Drum Kit/sounds/tom-1.mp3
  Web Development/Basic/Drum Kit/sounds/tom-2.mp3
  Web Development/Basic/Drum Kit/sounds/tom-3.mp3
  Web Development/Basic/Drum Kit/sounds/tom-4.mp3
  Web Development/Basic/Drum Kit/styles.css
Labels: Added Project, GSSoC22, Level1

#226 Calender - Desktop Application
  Desktop Application/Basic/C++/Calender/Calender.cpp
  Desktop Application/Basic/C++/Calender/README.md
  Desktop Application/Basic/C++/Calender/Screenshots/Code Snippet.png
  Desktop Application/Basic/C++/Calender/Screenshots/Test Cases.png
Labels: Added Project, GSSoC22, Level1

#238 #197 Uploading a new project "Sudoku-Solver"
  Desktop Application/Basic/C/Sudoku-Solver-C/Output.png
  Desktop Application/Basic/C/Sudoku-Solver-C/README.md
  Desktop Application/Basic/C/Sudoku-Solver-C/SudokuApproach1.c
  Desktop Application/Basic/C/Sudoku-Solver-C/SudokuBacktracking.c
  Desktop Application/Basic/C/Sudoku-Solver-C/SudokuBacktracking.cpp
Labels: Added Project, GSSoC22, Level1

#256 resolving issue number #251 as a part of GssoC'22
  Desktop Application/Basic/C++/Shopping List/main.cpp
Labels: Fixed Bug, GSSoC22, Level1

#240 Added Weather App Project
  Web Development/Basic/Weather App/Icons/pine-watt-2Hzmz15wGik-unsplash.jpg
  Web Development/Basic/Weather App/Icons/screenshot.png
  Web Development/Basic/Weather App/README.md
  Web Development/Basic/Weather App/app.js
  Web Development/Basic/Weather App/index.html
  Web Development/Basic/Weather App/style.css
Labels: Added Project, GSSoC22, Level1

#252 Covid-19 Timeseries Analysis with multiple model
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/README.md
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/covid-19-forecasting-using-arima.ipynb
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/covid-19-forecasting-using-prophet.ipynb
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/covid-19-prediction-using-neural-network.ipynb
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/3-together.png
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/README.md
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/ann.png
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/arima.png
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/country.png
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/linear1.png
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/lstm.png
  Machine Learning and Data Science/Intermediate/Covid_Third_Wave_Forecasting/results/prophet.png
Labels: Added Project, GSSoC22, Level2

#260 Added Vector Calculator Files
  Desktop Application/Basic/Python/Vector Calculator/calc.py
  Desktop Application/Basic/Python/Vector Calculator/documents/Capture.PNG
  Desktop Application/Basic/Python/Vector Calculator/readme.md
Labels: Added Project, GSSoC22, Level1

#253 casio added to webdev (#208 issue resovled) as a part of GssoC'22
  Web Development/Basic/Casio/Music_Note/A.wav
  Web Development/Basic/Casio/Music_Note/A_Drum.wav
  Web Development/Basic/Casio/Music_Note/B.wav
  Web Development/Basic/Casio/Music_Note/Bb_Drum.wav
  Web Development/Basic/Casio/Music_Note/C.wav
  Web Development/Basic/Casio/Music_Note/C1.wav
  Web Development/Basic/Casio/Music_Note/C1_Drum.wav
  Web Development/Basic/Casio/Music_Note/C_Drum.wav
  Web Development/Basic/Casio/Music_Note/C_s1.wav
  Web Development/Basic/Casio/Music_Note/D.wav
  Web Development/Basic/Casio/Music_Note/D1.wav
  Web Development/Basic/Casio/Music_Note/D1_Drum.wav
  Web Development/Basic/Casio/Music_Note/D_Drum.wav
  Web Development/Basic/Casio/Music_Note/D_s1.wav
  Web Development/Basic/Casio/Music_Note/Dq_Drum.wav
  Web Development/Basic/Casio/Music_Note/E.wav
  Web Development/Basic/Casio/Music_Note/E1.wav
  Web Development/Basic/Casio/Music_Note/E1_Drum.wav
  Web Development/Basic/Casio/Music_Note/F.wav
  Web Development/Basic/Casio/Music_Note/F1.wav
  Web Development/Basic/Casio/Music_Note/F_Drum.wav
  Web Development/Basic/Casio/Music_Note/G.wav
  Web Development/Basic/Casio/Music_Note/G_Drum.wav
  Web Development/Basic/Casio/Music_Note/G_s.wav
  Web Development/Basic/Casio/Music_Note/f1.jpg
  Web Development/Basic/Casio/README.md
  Web Development/Basic/Casio/demo.png
  Web Development/Basic/Casio/index.html
  Web Development/Basic/Casio/myscript.js
  Web Development/Basic/Casio/mystyle.css
Labels: Added Project, GSSoC22, Level2

#282 Added quiz website template
  Web Development/Basic/Quiz Website/README.md
  Web Development/Basic/Quiz Website/images/Google-Play-Icon3.jpg
  Web Development/Basic/Quiz Website/images/apple store.jpg
  Web Development/Basic/Quiz Website/images/girl2.png
  Web Development/Basic/Quiz Website/images/man 1.jpg
  Web Development/Basic/Quiz Website/images/man2.jpg
  Web Development/Basic/Quiz Website/index.html
  Web Development/Basic/Quiz Website/power to fly/Add_a_heading.png
  Web Development/Basic/Quiz Website/power to fly/animation.gif
  Web Development/Basic/Quiz Website/power to fly/img1.png
  Web Development/Basic/Quiz Website/power to fly/img2.jpg
  Web Development/Basic/Quiz Website/power to fly/img3.png
  Web Development/Basic/Quiz Website/pro.css
Labels: Added Project, GSSoC22, Level1

#286 Resolving issue #222, addding a beginner Friendly Project using Python and MySQL
  Desktop Application/Basic/Python/Student Assessment Card/code.py
  Desktop Application/Basic/Python/Student Assessment Card/readme.md
Labels: Added Project, GSSoC22, Level1

#279 Added BaseX Converter Files
  Web Development/Basic/BaseX_Calculator/app.js
  Web Development/Basic/BaseX_Calculator/index.html
  Web Development/Basic/BaseX_Calculator/readme.md
  Web Development/Basic/BaseX_Calculator/style.css
Labels: Added Project, GSSoC22, Level1

#287 Completed the issue #283 under GSSoC'22
  Web Development/Intermediate/animal adoption portal/README.md
  Web Development/Intermediate/animal adoption portal/adopt.php
  Web Development/Intermediate/animal adoption portal/adoption_portal.sql
  Web Development/Intermediate/animal adoption portal/contact.php
  Web Development/Intermediate/animal adoption portal/contactus.php
  Web Development/Intermediate/animal adoption portal/dbconfig.php
  Web Development/Intermediate/animal adoption portal/details.php
  Web Development/Intermediate/animal adoption portal/faq.php
  Web Development/Intermediate/animal adoption portal/images/1-1.jpg
  Web Development/Intermediate/animal adoption portal/images/1-2.jpg
  Web Development/Intermediate/animal adoption portal/images/1-4.jpg
  Web Development/Intermediate/animal adoption portal/images/1.jpg
  Web Development/Intermediate/animal adoption portal/images/2-1.jpg
  Web Development/Intermediate/animal adoption portal/images/2-2.jpg
  Web Development/Intermediate/animal adoption portal/images/2-3.jpg
  Web Development/Intermediate/animal adoption portal/images/2.jpg
  Web Development/Intermediate/animal adoption portal/images/3-1.jpg
  Web Development/Intermediate/animal adoption portal/images/3-2.jpg
  Web Development/Intermediate/animal adoption portal/images/3-3.jpg
  Web Development/Intermediate/animal adoption portal/images/3.jpg
  Web Development/Intermediate/animal adoption portal/images/4-1.jpg
  Web Development/Intermediate/animal adoption portal/images/4-2.jpg
  Web Development/Intermediate/animal adoption portal/images/4-3.jpg
  Web Development/Intermediate/animal adoption portal/images/4.jpg
  Web Development/Intermediate/animal adoption portal/images/5-1.jpg
  Web Development/Intermediate/animal adoption portal/images/5-2.jpg
  Web Development/Intermediate/animal adoption portal/images/5-3.jpg
  Web Development/Intermediate/animal adoption portal/images/6-1.jpg
  Web Development/Intermediate/animal adoption portal/images/6-2.jpg
  Web Development/Intermediate/animal adoption portal/images/6-3.jpg
  Web Development/Intermediate/animal adoption portal/images/7-1.jpg
  Web Development/Intermediate/animal adoption portal/images/7-2.jpg
  Web Development/Intermediate/animal adoption portal/images/7-3.jpg
  Web Development/Intermediate/animal adoption portal/images/8-1.jpg
  Web Development/Intermediate/animal adoption portal/images/8-2.jpg
  Web Development/Intermediate/animal adoption portal/images/bg.jpg
  Web Development/Intermediate/animal adoption portal/images/bg1.jpeg
  Web Development/Intermediate/animal adoption portal/images/bg2.jpeg
  Web Development/Intermediate/animal adoption portal/index.php
Labels: Added Project, GSSoC22, Level2

#285 project count updated
  README.md
Labels: Updating Project

#288 Added Vaccination Centre Locator
  Desktop Application/Basic/Python/Vaccination Centre Locator/Readme.md
  Desktop Application/Basic/Python/Vaccination Centre Locator/vaccination.py
Labels: Added Project, GSSoC22, Level1

#301 Image Request Feature added
  Desktop Application/Basic/Python/Image Request/Readme.md
  Desktop Application/Basic/Python/Image Request/container.jpg
  Desktop Application/Basic/Python/Image Request/img.py
Labels: Added Project, GSSoC22, Level1

#300 Add card check
  Desktop Application/Basic/C++/Credit Card Checker/Documents/Screenshot1.png
  Desktop Application/Basic/C++/Credit Card Checker/Documents/Screenshot2.png
  Desktop Application/Basic/C++/Credit Card Checker/Documents/Screenshot3.png
  Desktop Application/Basic/C++/Credit Card Checker/Documents/Screenshot4.png
  Desktop Application/Basic/C++/Credit Card Checker/README.md
  Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
Labels: Added Project, GSSoC22, Level1

#266 Created Calculator using python GUI
  Desktop Application/Basic/Python/Calculator_GUI/Calculator_GUI.py
  Desktop Application/Basic/Python/Calculator_GUI/Images/Screenshot from 2022-03-04 22-25-32.png
  Desktop Application/Basic/Python/Calculator_GUI/Images/Screenshot from 2022-03-04 22-25-51.png
  Desktop Application/Basic/Python/Calculator_GUI/Images/Screenshot from 2022-03-04 22-25-59.png
  Desktop Application/Basic/Python/Calculator_GUI/Readme.md
Labels: Added Project, GSSoC22, Level1

#295 Tic-Tac-Toe game using java
  Desktop Application/Basic/Java/TicTacToe/Images/tictactoe.png
  Desktop Application/Basic/Java/TicTacToe/Images/tictactoe1.png
  Desktop Application/Basic/Java/TicTacToe/README.md
  Desktop Application/Basic/Java/TicTacToe/bin/play/TicTacToe.class
  Desktop Application/Basic/Java/TicTacToe/src/play/TicTacToe.java
Labels: Added Project, GSSoC22, Level1

#296 added algorithm visualiser app
  Desktop Application/Intermediate/Python/Algorithm_visualiser/Images/AlgorithmVisualiser.png
  Desktop Application/Intermediate/Python/Algorithm_visualiser/README.md
  Desktop Application/Intermediate/Python/Algorithm_visualiser/requirements.txt
  Desktop Application/Intermediate/Python/Algorithm_visualiser/visualiser.py
Labels: Added Project, GSSoC22, Level2

#269 Gas Leakage Detection Software
  IOT(Internet of Things)/Intermediate/README.md
  IOT(Internet of Things)/Intermediate/gas leakage detection/Arduino_Firmata_Code/Arduino_Firmata_Code.ino
  IOT(Internet of Things)/Intermediate/gas leakage detection/README.md
  IOT(Internet of Things)/Intermediate/gas leakage detection/alarm_run.py
  IOT(Internet of Things)/Intermediate/gas leakage detection/requirements.txt
  IOT(Internet of Things)/README.md
Labels: Added Project, GSSoC22, Level1

#310 Roll dice game
  Web Development/Basic/Roll Dice/README.md
  Web Development/Basic/Roll Dice/Screenshots/initialScreen.png
  Web Development/Basic/Roll Dice/Screenshots/midGame.png
  Web Development/Basic/Roll Dice/Screenshots/midGame2.png
  Web Development/Basic/Roll Dice/Screenshots/winScreen.png
  Web Development/Basic/Roll Dice/img/dice-1.png
  Web Development/Basic/Roll Dice/img/dice-2.png
  Web Development/Basic/Roll Dice/img/dice-3.png
  Web Development/Basic/Roll Dice/img/dice-4.png
  Web Development/Basic/Roll Dice/img/dice-5.png
  Web Development/Basic/Roll Dice/img/dice-6.png
  Web Development/Basic/Roll Dice/index.html
  Web Development/Basic/Roll Dice/script.js
  Web Development/Basic/Roll Dice/style.css
Labels: Added Project, GSSoC22, Level1

#312 Added issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/proposal.yaml
Labels: enhancement, GSSoC22, Level1

#319 Medical insurance prediction
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.39.14 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.39.29 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.39.42 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.39.53 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.42.29 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.42.40 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/Screenshot 2022-03-04 at 7.42.56 PM.png
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Img/save
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Insurance_Cost_Prediction.ipynb
  Machine Learning and Data Science/Basic/Medical Insurance Prediction/Readme.md
Labels: Added Project, GSSoC22, Level1

#337 Readme fix
  Desktop Application/Basic/C/School management/readme.md
  Desktop Application/Basic/C/Sudoku-Solver-C/README.md
  Desktop Application/Basic/Java/BookLibrary/README.md
  Desktop Application/Basic/Java/BrickBreaker/README.md
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/README.md
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/Screenshot/1..jpg
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/Screenshot/2.jpg
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/Screenshot/3.jpg
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/Screenshot/4.jpg
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/Screenshot/5.jpg
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/Tic Tac Toe AI.cpp
  Desktop Application/Intermediate/C++/Tic-Tac-Toe-AI-Integrated/toss.jpg
  Desktop Application/README.md
  Machine Learning and Data Science/Advanced/Timeline Analysis Covid-19/COVID19 Analysis.ipynb
  Machine Learning and Data Science/Advanced/Timeline Analysis Covid-19/README.md
  Machine Learning and Data Science/README.md
  Mobile Applications/README.md
  README.md
  Web Development/README.md
Labels: documentation, GSSoC22, Level1

#324 Added new Project : Water Reminder
  Desktop Application/Basic/Python/Water Reminder/Readme.md
  Desktop Application/Basic/Python/Water Reminder/icon.ico
  Desktop Application/Basic/Python/Water Reminder/images/Snip.png
  Desktop Application/Basic/Python/Water Reminder/main.py
Labels: Added Project, GSSoC22, Level1

#298 EDA on Netflix Data
  Machine Learning and Data Science/Basic/EDA on Netflix Data/EDAonNETFLIX (1).ipynb
  Machine Learning and Data Science/Basic/EDA on Netflix Data/Readme.md
Labels: Added Project, GSSoC22, Level1

#334 fix a bug when the user enters a leap year (issue #314) as a part of GSSoC22
  Desktop Application/Basic/C++/Calender/Calender.cpp
  Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
Labels: enhancement, Fixed Bug, GSSoC22, Level1

#325 Linear Regression from scratch with example has been implemented
  Machine Learning and Data Science/Basic/Linear Regression from scratch/HTN.png
  Machine Learning and Data Science/Basic/Linear Regression from scratch/LinearReg.py
  Machine Learning and Data Science/Basic/Linear Regression from scratch/README.md
  Machine Learning and Data Science/Basic/Linear Regression from scratch/plot.png
  Machine Learning and Data Science/Basic/Linear Regression from scratch/salary_data.csv
  Machine Learning and Data Science/Basic/Linear Regression from scratch/wbt.png
Labels: Added Project, GSSoC22, Level1

#376 Added glowing icons
  Web Development/Basic/Glowing icons with hover/README.md
  Web Development/Basic/Glowing icons with hover/index.html
  Web Development/Basic/Glowing icons with hover/style.css
Labels: Added Project, GSSoC22, Level1

#335 Added color code converter webpage files
  Web Development/Basic/Color_Code_Converter/assets/css/style.css
  Web Development/Basic/Color_Code_Converter/assets/media/Capture.PNG
  Web Development/Basic/Color_Code_Converter/index.html
  Web Development/Basic/Color_Code_Converter/readme.md
  Web Development/Basic/Color_Code_Converter/scripts/app.js
Labels: Added Project, GSSoC22, Level1

#353 enhanced navigation-bar and submit button issue
  Web Development/Basic/Tourist Places/Aboutus.html
  Web Development/Basic/Tourist Places/Activities.html
  Web Development/Basic/Tourist Places/Contactus.html
  Web Development/Basic/Tourist Places/Gallery.html
  Web Development/Basic/Tourist Places/andamaan.html
  Web Development/Basic/Tourist Places/bestimetovisit.html
  Web Development/Basic/Tourist Places/coorg.html
  Web Development/Basic/Tourist Places/darjeeling.html
  Web Development/Basic/Tourist Places/delhi.html
  Web Development/Basic/Tourist Places/feedback.html
  Web Development/Basic/Tourist Places/goa.html
  Web Development/Basic/Tourist Places/help.html
  Web Development/Basic/Tourist Places/hotelsahara.html
  Web Development/Basic/Tourist Places/index.html
  Web Development/Basic/Tourist Places/jw.html
  Web Development/Basic/Tourist Places/kc.html
  Web Development/Basic/Tourist Places/lalit.html
  Web Development/Basic/Tourist Places/login.html
  Web Development/Basic/Tourist Places/manali.html
  Web Development/Basic/Tourist Places/mumbai.html
  Web Development/Basic/Tourist Places/oberoi.html
  Web Development/Basic/Tourist Places/shimla.html
  Web Development/Basic/Tourist Places/signup.html
  Web Development/Basic/Tourist Places/udaipur.html
Labels: enhancement, Fixed Bug, GSSoC22, Level1

#375 Added Motivator
  Desktop Application/Basic/Python/Motivational Quote Speaker/Readme.md
  Desktop Application/Basic/Python/Motivational Quote Speaker/motivator.py
Labels: Added Project, GSSoC22, Level1

#374 Tip Calculator issue #224
  Web Development/Basic/TipCalculator/README.md
  Web Development/Basic/TipCalculator/index.html
  Web Development/Basic/TipCalculator/screenshots/TipCalculator.PNG
  Web Development/Basic/TipCalculator/script.js
  Web Development/Basic/TipCalculator/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#362 Donation website model
  Web Development/Basic/Donation Website/README.md
  Web Development/Basic/Donation Website/image.jpg
  Web Development/Basic/Donation Website/index.html
  Web Development/Basic/Donation Website/logo.png
  Web Development/Basic/Donation Website/style.css
Labels: Added Project, GSSoC22, Level1

#382 Added Arduino_Analog_Input files
  IOT(Internet of Things)/Basic/Arduino_Analog_Input/Setup.png
  IOT(Internet of Things)/Basic/Arduino_Analog_Input/analog_input.ino
  IOT(Internet of Things)/Basic/Arduino_Analog_Input/readme.md
Labels: Added Project, GSSoC22, Level1

#381 Added Customer Review webapp files
  Web Development/Intermediate/Customer Review Webapp/app.py
  Web Development/Intermediate/Customer Review Webapp/readme.md
  Web Development/Intermediate/Customer Review Webapp/reviews.csv
  Web Development/Intermediate/Customer Review Webapp/templates/index.html
Labels: Added Project, GSSoC22, Level1

#377 Added Form Validation to Basic Web Development
  Web Development/Basic/Form Validation/README.md
  Web Development/Basic/Form Validation/formValidation.js
  Web Development/Basic/Form Validation/image/README/1646806722983.png
  Web Development/Basic/Form Validation/image/README/1646807643240.png
  Web Development/Basic/Form Validation/index.html
  Web Development/Basic/Form Validation/onlineCourses.jpg
  Web Development/Basic/Form Validation/style.css
Labels: Added Project, GSSoC22, Level1

#385 Added Flipbook Project
  Web Development/Basic/flipbook/README.md
  Web Development/Basic/flipbook/index.html
  Web Development/Basic/flipbook/script.js
  Web Development/Basic/flipbook/style.css
  Web Development/Basic/flipbook/turn.js
Labels: Added Project, GSSoC22, Level1

#368 Flutter Basic BMI Calculator App
  Mobile Applications/Basic/BMI Calculator/README.md
  Mobile Applications/Basic/BMI Calculator/android/app/build.gradle
  Mobile Applications/Basic/BMI Calculator/android/app/src/debug/AndroidManifest.xml
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/AndroidManifest.xml
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/kotlin/com/example/bmi_calculator/MainActivity.kt
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/drawable-v21/launch_background.xml
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/drawable/launch_background.xml
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/values-night/styles.xml
  Mobile Applications/Basic/BMI Calculator/android/app/src/main/res/values/styles.xml
  Mobile Applications/Basic/BMI Calculator/android/app/src/profile/AndroidManifest.xml
  Mobile Applications/Basic/BMI Calculator/android/build.gradle
  Mobile Applications/Basic/BMI Calculator/android/gradle.properties
  Mobile Applications/Basic/BMI Calculator/android/gradle/wrapper/gradle-wrapper.properties
  Mobile Applications/Basic/BMI Calculator/android/settings.gradle
  Mobile Applications/Basic/BMI Calculator/assets/images/icon.png
  Mobile Applications/Basic/BMI Calculator/ios/Flutter/AppFrameworkInfo.plist
  Mobile Applications/Basic/BMI Calculator/ios/Flutter/Debug.xcconfig
  Mobile Applications/Basic/BMI Calculator/ios/Flutter/Release.xcconfig
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcodeproj/project.pbxproj
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcworkspace/contents.xcworkspacedata
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Mobile Applications/Basic/BMI Calculator/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppDelegate.swift
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/1024.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/114.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/120.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/180.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/29.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/40.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/57.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/58.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/60.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/80.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/87.png
  Mobile Applications/Basic/BMI Calculator/ios/Runner/AppIcon.appiconset/Contents.json
  Mobile Applications/Basic/BMI Calculator/ios/Runner/Base.lproj/LaunchScreen.storyboard
  Mobile Applications/Basic/BMI Calculator/ios/Runner/Base.lproj/Main.storyboard
  Mobile Applications/Basic/BMI Calculator/ios/Runner/Info.plist
  Mobile Applications/Basic/BMI Calculator/ios/Runner/Runner-Bridging-Header.h
  Mobile Applications/Basic/BMI Calculator/lib/container_box.dart
  Mobile Applications/Basic/BMI Calculator/lib/data_container.dart
  Mobile Applications/Basic/BMI Calculator/lib/main.dart
  Mobile Applications/Basic/BMI Calculator/lib/main_screen.dart
  Mobile Applications/Basic/BMI Calculator/pubspec.lock
  Mobile Applications/Basic/BMI Calculator/pubspec.yaml
  Mobile Applications/Basic/BMI Calculator/test/widget_test.dart
Labels: Under-review, GSSoC22, Level1

#399 Added courier management system under Gssoc22
  Web Development/Advanced/courier management system/README.md
  Web Development/Advanced/courier management system/adminaddloc.php
  Web Development/Advanced/courier management system/adminaddstaff.php
  Web Development/Advanced/courier management system/adminallcenters.php
  Web Development/Advanced/courier management system/adminallcou.php
  Web Development/Advanced/courier management system/adminallstaff.php
  Web Development/Advanced/courier management system/adminhome.php
  Web Development/Advanced/courier management system/adminlogin.php
  Web Development/Advanced/courier management system/adminnewcourier.php
  Web Development/Advanced/courier management system/adminviewcenter.php
  Web Development/Advanced/courier management system/adminviewcou.php
  Web Development/Advanced/courier management system/adminviewstaff.php
  Web Development/Advanced/courier management system/cms.sql
  Web Development/Advanced/courier management system/db.php
  Web Development/Advanced/courier management system/details.php
  Web Development/Advanced/courier management system/images/BG1.png
  Web Development/Advanced/courier management system/images/bg.jpg
  Web Development/Advanced/courier management system/images/c1.png
  Web Development/Advanced/courier management system/images/courier.jpg
  Web Development/Advanced/courier management system/images/courier1.png
  Web Development/Advanced/courier management system/images/courier2.jpg
  Web Development/Advanced/courier management system/images/location.png
  Web Development/Advanced/courier management system/images/staff.png
  Web Development/Advanced/courier management system/index.php
  Web Development/Advanced/courier management system/logout.php
  Web Development/Advanced/courier management system/nav1.php
  Web Development/Advanced/courier management system/nav2.php
  Web Development/Advanced/courier management system/nav3.php
  Web Development/Advanced/courier management system/staffallcenters.php
  Web Development/Advanced/courier management system/staffallcou.php
  Web Development/Advanced/courier management system/staffallstaff.php
  Web Development/Advanced/courier management system/staffhome.php
  Web Development/Advanced/courier management system/stafflogin.php
  Web Development/Advanced/courier management system/staffnewcourier.php
  Web Development/Advanced/courier management system/staffviewcenter.php
  Web Development/Advanced/courier management system/staffviewcou.php
  Web Development/Advanced/courier management system/staffviewstaff.php
  Web Development/Advanced/courier management system/style.css
  Web Development/Advanced/courier management system/track.php
  Web Development/Advanced/courier management system/updatecou.php
  Web Development/Advanced/courier management system/updatestaff.php
  Web Development/Advanced/courier management system/uploc.php
  Web Development/Advanced/courier management system/yourcourier.php
Labels: Added Project, GSSoC22, Level2

#401 Added Instagram Login Page Clone to Basic Web Development Project section
  Web Development/Basic/Instagram Login Page Clone/README.md
  Web Development/Basic/Instagram Login Page Clone/igicon.png
  Web Development/Basic/Instagram Login Page Clone/index.css
  Web Development/Basic/Instagram Login Page Clone/index.html
  Web Development/Basic/Instagram Login Page Clone/meta.png
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#402 Enhance calendar
  Desktop Application/Basic/C++/Calender/Calender.cpp
  Desktop Application/Basic/C++/Calender/README.md
Labels: enhancement, GSSoC22, Level1

#373 Added PDF Table Scraper Files
  Desktop Application/Basic/Python/PDF_Table_Scraper/readme.md
  Desktop Application/Basic/Python/PDF_Table_Scraper/scraper.py
Labels: Added Project, GSSoC22, Level1

#370 Clock desktop application added
  Desktop Application/Basic/Python/Digital-Clock/AntiqueMellowAmericanrobin-max-1mb.gif
  Desktop Application/Basic/Python/Digital-Clock/DIGITAL.TXT
  Desktop Application/Basic/Python/Digital-Clock/DS-DIGI.TTF
  Desktop Application/Basic/Python/Digital-Clock/DS-DIGIB.TTF
  Desktop Application/Basic/Python/Digital-Clock/DS-DIGII.TTF
  Desktop Application/Basic/Python/Digital-Clock/DS-DIGIT.TTF
  Desktop Application/Basic/Python/Digital-Clock/Readme.md
  Desktop Application/Basic/Python/Digital-Clock/main.py
Labels: Added Project, GSSoC22, Level1

#403 Single Neural Network
  Machine Learning and Data Science/Basic/Single Neural Network/Readme.md
  Machine Learning and Data Science/Basic/Single Neural Network/Single Layer Percepton Neural Network.ipynb
Labels: Added Project, GSSoC22, Level1

#404 Fixing the issue #390
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/1_Create.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/2_DisplayDirectory.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/3_DisplayByTags.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/4_Modify.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/5_Search.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/6_Delete.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op1.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op2.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op3.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op4.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op5.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op6.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op7_exit.png
  Desktop Application/Intermediate/C/PhoneBook_Management_System/PhoneBook.c
  Desktop Application/Intermediate/C/PhoneBook_Management_System/README.md
Labels: Added Project, GSSoC22, Level2

#398 MyOnlineMeals.com
  Web Development/Basic/MyOnlineMeals/1.jpg
  Web Development/Basic/MyOnlineMeals/2.jpg
  Web Development/Basic/MyOnlineMeals/About.html
  Web Development/Basic/MyOnlineMeals/README.md
  Web Development/Basic/MyOnlineMeals/Zomato.png
  Web Development/Basic/MyOnlineMeals/about.css
  Web Development/Basic/MyOnlineMeals/aroma-906137_1920.jpg
  Web Development/Basic/MyOnlineMeals/back.jpg
  Web Development/Basic/MyOnlineMeals/backgr.jpg
  Web Development/Basic/MyOnlineMeals/backgro.jpg
  Web Development/Basic/MyOnlineMeals/cbug.jpg
  Web Development/Basic/MyOnlineMeals/chef.jpg
  Web Development/Basic/MyOnlineMeals/chepas.jpg
  Web Development/Basic/MyOnlineMeals/chickmomo.jpg
  Web Development/Basic/MyOnlineMeals/cnoo.jpg
  Web Development/Basic/MyOnlineMeals/contact page.png
  Web Development/Basic/MyOnlineMeals/contact.html
  Web Development/Basic/MyOnlineMeals/contact.jpg
  Web Development/Basic/MyOnlineMeals/css/phone.css
  Web Development/Basic/MyOnlineMeals/css/style.css
  Web Development/Basic/MyOnlineMeals/download - Copy.jpg
  Web Development/Basic/MyOnlineMeals/download.jpg
  Web Development/Basic/MyOnlineMeals/final - Copy.jpg
  Web Development/Basic/MyOnlineMeals/final.html
  Web Development/Basic/MyOnlineMeals/final.jpg
  Web Development/Basic/MyOnlineMeals/img/bg.jpg
  Web Development/Basic/MyOnlineMeals/img/img 2.jpg
  Web Development/Basic/MyOnlineMeals/img/img1.png
  Web Development/Basic/MyOnlineMeals/img/logo s.jpg
  Web Development/Basic/MyOnlineMeals/index.html
  Web Development/Basic/MyOnlineMeals/item page.png
  Web Development/Basic/MyOnlineMeals/landingpage.png
  Web Development/Basic/MyOnlineMeals/ord.html
  Web Development/Basic/MyOnlineMeals/order.css
  Web Development/Basic/MyOnlineMeals/order.html
  Web Development/Basic/MyOnlineMeals/papizza.jpg
  Web Development/Basic/MyOnlineMeals/pasta.html
  Web Development/Basic/MyOnlineMeals/pepperonipizza.jpg
  Web Development/Basic/MyOnlineMeals/pizza.png
  Web Development/Basic/MyOnlineMeals/ros - Copy.jpeg
  Web Development/Basic/MyOnlineMeals/ros.jpeg
  Web Development/Basic/MyOnlineMeals/service.png
  Web Development/Basic/MyOnlineMeals/services.html
  Web Development/Basic/MyOnlineMeals/spaghetti-1932466_1920.jpg
  Web Development/Basic/MyOnlineMeals/sweeet1 - Copy.jpg
  Web Development/Basic/MyOnlineMeals/sweeet1.jpg
  Web Development/Basic/MyOnlineMeals/tpas.jpg
  Web Development/Basic/MyOnlineMeals/vbug.jpg
  Web Development/Basic/MyOnlineMeals/vmomos.jpg
  Web Development/Basic/MyOnlineMeals/vnoo.jpg
Labels: Added Project, GSSoC22, Level1

#411 Added Discord Clone files
  Web Development/Basic/Discord_App_Clone/assets/css/bootstrap.css
  Web Development/Basic/Discord_App_Clone/assets/css/bootstrap.css.map
  Web Development/Basic/Discord_App_Clone/assets/css/style.css
  Web Development/Basic/Discord_App_Clone/assets/media/FriendsImages/Avatar0.png
  Web Development/Basic/Discord_App_Clone/assets/media/FriendsImages/Avatar1.png
  Web Development/Basic/Discord_App_Clone/assets/media/ServersCol/GSSoC_Server.webp
  Web Development/Basic/Discord_App_Clone/assets/media/ServersCol/Server0.webp
  Web Development/Basic/Discord_App_Clone/assets/media/ServersCol/Server1.webp
  Web Development/Basic/Discord_App_Clone/assets/media/ServersCol/discord_server_icon.png
  Web Development/Basic/Discord_App_Clone/assets/media/Tab_Icon.svg
  Web Development/Basic/Discord_App_Clone/home.html
  Web Development/Basic/Discord_App_Clone/readme.md
  Web Development/Basic/Discord_App_Clone/scripts/bootstrap.bundle.js
  Web Development/Basic/Discord_App_Clone/scripts/bootstrap.bundle.js.map
Labels: Added Project, GSSoC22, Level1

#406 project added
  Web Development/Basic/Sticky Notes/README.md
  Web Development/Basic/Sticky Notes/index.html
  Web Development/Basic/Sticky Notes/style.js
  Web Development/Basic/Sticky Notes/styling.css
Labels: Added Project, GSSoC22, Level1

#416 Added basic calculator app
  Web Development/Basic/Basic Calculator App/Readme.md
  Web Development/Basic/Basic Calculator App/index.html
  Web Development/Basic/Basic Calculator App/script.js
  Web Development/Basic/Basic Calculator App/style.css
Labels: Added Project, GSSoC22, Level1

#422 Contact form update
  Web Development/Basic/Contact Form/ContactForm.css
  Web Development/Basic/Contact Form/README.md
  Web Development/Basic/Contact Form/ScreenShot.jpg
  Web Development/Basic/Contact Form/ScreenShot.png
  Web Development/Basic/Contact Form/index.html
  Web Development/Basic/Contact Form/vanilla-tilt.js
Labels: enhancement, GSSoC22, Level1

#424 Google Homepage Clone Added
  Web Development/Basic/Google Homepage Clone/images/favicon.jpg
  Web Development/Basic/Google Homepage Clone/images/logo.jpg
  Web Development/Basic/Google Homepage Clone/index.html
  Web Development/Basic/Google Homepage Clone/main.js
  Web Development/Basic/Google Homepage Clone/readme.md
  Web Development/Basic/Google Homepage Clone/style.css
  Web Development/README.md
Labels: Added Project, GSSoC22, Level1

#410 Updated Readme.md #299 #331
  Desktop Application/Basic/Python/Snake_Game/Readme.md
  Desktop Application/Basic/Python/Snake_Game/Snake_Game.py
  Desktop Application/Basic/Python/Snake_Game/Snake_Game_gif.gif
Labels: Added Project, GSSoC22, Level1

#333 Nodemailer #330
  Web Development/Basic/NodeMailer/README.md
  Web Development/Basic/NodeMailer/app.js
  Web Development/Basic/NodeMailer/package-lock.json
  Web Development/Basic/NodeMailer/package.json
  Web Development/Basic/NodeMailer/public/css/css
  Web Development/Basic/NodeMailer/public/css/style.css
  Web Development/Basic/NodeMailer/views/contact.handlebars
  Web Development/Basic/Ping-pong-Python/__pycache__/ball.cpython-38.pyc
  Web Development/Basic/Ping-pong-Python/__pycache__/ball.cpython-39.pyc
  Web Development/Basic/Ping-pong-Python/__pycache__/paddle.cpython-38.pyc
  Web Development/Basic/Ping-pong-Python/__pycache__/paddle.cpython-39.pyc
  Web Development/Basic/Ping-pong-Python/__pycache__/scoreboard.cpython-38.pyc
  Web Development/Basic/Ping-pong-Python/__pycache__/scoreboard.cpython-39.pyc
  Web Development/Basic/Ping-pong-Python/ball.py
  Web Development/Basic/Ping-pong-Python/main.py
  Web Development/Basic/Ping-pong-Python/paddle.py
  Web Development/Basic/Ping-pong-Python/scoreboard.py
Labels: Added Project, GSSoC22, Level1

#426 Added function plotter files
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Error_1.png
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Error_2.png
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Error_3.png
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Error_4.png
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Working_1.png
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Working_2.png
  Desktop Application/Basic/Python/Function-Ploter/Examples_ScreenShots/Working_3.png
  Desktop Application/Basic/Python/Function-Ploter/Plotter.py
  Desktop Application/Basic/Python/Function-Ploter/README.md
  Desktop Application/Basic/Python/Function-Ploter/requirements.txt
Labels: Added Project, GSSoC22, Level1

#427 Added cubic equation solver files
  Web Development/Basic/Cubic_Equation_Solver/assets/css/bootstrap.css
  Web Development/Basic/Cubic_Equation_Solver/assets/css/bootstrap.css.map
  Web Development/Basic/Cubic_Equation_Solver/assets/css/style.css
  Web Development/Basic/Cubic_Equation_Solver/index.html
  Web Development/Basic/Cubic_Equation_Solver/readme.md
  Web Development/Basic/Cubic_Equation_Solver/scripts/app.js
  Web Development/Basic/Cubic_Equation_Solver/scripts/bootstrap.bundle.js
  Web Development/Basic/Cubic_Equation_Solver/scripts/bootstrap.bundle.js.map
Labels: Added Project, GSSoC22, Level1

#428 Added post-memories-app
  Web Development/Intermediate/post-memories-app/README.md
  Web Development/Intermediate/post-memories-app/client/.gitignore
  Web Development/Intermediate/post-memories-app/client/README.md
  Web Development/Intermediate/post-memories-app/client/package-lock.json
  Web Development/Intermediate/post-memories-app/client/package.json
  Web Development/Intermediate/post-memories-app/client/public/index.html
  Web Development/Intermediate/post-memories-app/client/src/App.js
  Web Development/Intermediate/post-memories-app/client/src/Components/Form/Form.jsx
  Web Development/Intermediate/post-memories-app/client/src/Components/Form/styles.js
  Web Development/Intermediate/post-memories-app/client/src/Components/Images/memories.png
  Web Development/Intermediate/post-memories-app/client/src/Components/Posts/Post/Post.jsx
  Web Development/Intermediate/post-memories-app/client/src/Components/Posts/Post/styles.js
  Web Development/Intermediate/post-memories-app/client/src/Components/Posts/Posts.jsx
  Web Development/Intermediate/post-memories-app/client/src/Components/Posts/styles.js
  Web Development/Intermediate/post-memories-app/client/src/Constants/actionTypes.js
  Web Development/Intermediate/post-memories-app/client/src/actions/posts.js
  Web Development/Intermediate/post-memories-app/client/src/api/index.js
  Web Development/Intermediate/post-memories-app/client/src/index.css
  Web Development/Intermediate/post-memories-app/client/src/index.js
  Web Development/Intermediate/post-memories-app/client/src/reducers/index.js
  Web Development/Intermediate/post-memories-app/client/src/reducers/posts.js
  Web Development/Intermediate/post-memories-app/client/src/reportWebVitals.js
  Web Development/Intermediate/post-memories-app/client/src/styles.js
  Web Development/Intermediate/post-memories-app/server/.env
  Web Development/Intermediate/post-memories-app/server/.env.example
  Web Development/Intermediate/post-memories-app/server/.gitignore
  Web Development/Intermediate/post-memories-app/server/components/db.js
  Web Development/Intermediate/post-memories-app/server/controllers/posts.js
  Web Development/Intermediate/post-memories-app/server/index.js
  Web Development/Intermediate/post-memories-app/server/models/postMessages.js
  Web Development/Intermediate/post-memories-app/server/package-lock.json
  Web Development/Intermediate/post-memories-app/server/package.json
  Web Development/Intermediate/post-memories-app/server/routes/posts.js
Labels: Added Project, GSSoC22, Level2

#430 Add SCRABBLE
  Desktop Application/Basic/C++/Scrabble/README.md
  Desktop Application/Basic/C++/Scrabble/scrabble.cpp
Labels: Added Project, GSSoC22, Level1

#429 TicTacToe Game
  Mobile Applications/Basic/TicTacToe Game/.idea/.gitignore
  Mobile Applications/Basic/TicTacToe Game/.idea/.name
  Mobile Applications/Basic/TicTacToe Game/.idea/compiler.xml
  Mobile Applications/Basic/TicTacToe Game/.idea/gradle.xml
  Mobile Applications/Basic/TicTacToe Game/.idea/misc.xml
  Mobile Applications/Basic/TicTacToe Game/README.md
  Mobile Applications/Basic/TicTacToe Game/app/build.gradle
  Mobile Applications/Basic/TicTacToe Game/app/proguard-rules.pro
  Mobile Applications/Basic/TicTacToe Game/app/src/androidTest/java/com/example/tictactoe/ExampleInstrumentedTest.kt
  Mobile Applications/Basic/TicTacToe Game/app/src/main/AndroidManifest.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/java/com/example/tictactoe/MainActivity.kt
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/drawable/ic_launcher_background.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/drawable/roundstyle.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/layout/activity_main.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/values-night/themes.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/values/colors.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/values/strings.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/main/res/values/themes.xml
  Mobile Applications/Basic/TicTacToe Game/app/src/test/java/com/example/tictactoe/ExampleUnitTest.kt
  Mobile Applications/Basic/TicTacToe Game/build.gradle
  Mobile Applications/Basic/TicTacToe Game/gradle.properties
  Mobile Applications/Basic/TicTacToe Game/gradle/wrapper/gradle-wrapper.jar
  Mobile Applications/Basic/TicTacToe Game/gradle/wrapper/gradle-wrapper.properties
  Mobile Applications/Basic/TicTacToe Game/gradlew
  Mobile Applications/Basic/TicTacToe Game/gradlew.bat
  Mobile Applications/Basic/TicTacToe Game/settings.gradle
Labels: Added Project, GSSoC22, Level1
