Repository Kushal997-das/Project-Guidance, pull requests merged in 2023-10, with the labels that each got.

#925 WEB DEVELOPMENT - BULLSEYE GAME
  Web Development/Basic/Bullseye Game/README.md
  Web Development/Basic/Bullseye Game/index.html
  Web Development/Basic/Bullseye Game/script.js
  Web Development/Basic/Bullseye Game/style.css
Labels: Added Project, hacktoberfest-acepted

#938 Added React Calculator
  Web Development/Basic/React Calculator/.gitignore
  Web Development/Basic/React Calculator/README.md
  Web Development/Basic/React Calculator/calc_ss.png
  Web Development/Basic/React Calculator/index.js
  Web Development/Basic/React Calculator/package-lock.json
  Web Development/Basic/React Calculator/package.json
  Web Development/Basic/React Calculator/public/favicon.ico
  Web Development/Basic/React Calculator/public/index.html
  Web Development/Basic/React Calculator/public/logo192.png
  Web Development/Basic/React Calculator/public/logo512.png
  Web Development/Basic/React Calculator/public/manifest.json
  Web Development/Basic/React Calculator/public/robots.txt
  Web Development/Basic/React Calculator/src/App.js
  Web Development/Basic/React Calculator/src/components/Button.css
  Web Development/Basic/React Calculator/src/components/Button.js
  Web Development/Basic/React Calculator/src/components/ButtonBox.css
  Web Development/Basic/React Calculator/src/components/ButtonBox.js
  Web Development/Basic/React Calculator/src/components/Screen.css
  Web Development/Basic/React Calculator/src/components/Screen.js
  Web Development/Basic/React Calculator/src/components/Wrapper.css
  Web Development/Basic/React Calculator/src/components/Wrapper.js
  Web Development/Basic/React Calculator/src/index.css
  Web Development/Basic/React Calculator/src/index.js
  Web Development/README.md
Labels: Added Project, hacktoberfest-acepted

#939 Hangman game added
  Web Development/Basic/Hangman Game/Hangman.png
  Web Development/Basic/Hangman Game/README.md
  Web Development/Basic/Hangman Game/images/0.jpg
  Web Development/Basic/Hangman Game/images/1.jpg
  Web Development/Basic/Hangman Game/images/2.jpg
  Web Development/Basic/Hangman Game/images/3.jpg
  Web Development/Basic/Hangman Game/images/4.jpg
  Web Development/Basic/Hangman Game/images/5.jpg
  Web Development/Basic/Hangman Game/images/6.jpg
  Web Development/Basic/Hangman Game/index.html
  Web Development/Basic/Hangman Game/js/hangman.js
  Web Development/Basic/Hangman Game/script.js
  Web Development/Basic/Hangman Game/style.css
  Web Development/README.md
Labels: Added Project

#947 Added Home Security System
  IOT(Internet of Things)/Intermediate/Home Security System/Images/home_security_system.PNG
  IOT(Internet of Things)/Intermediate/Home Security System/Images/home_security_system.mp4
  IOT(Internet of Things)/Intermediate/Home Security System/README.md
  IOT(Internet of Things)/Intermediate/Home Security System/home_security_system.cpp
  IOT(Internet of Things)/Intermediate/Home Security System/requirements.txt
  IOT(Internet of Things)/README.md
Labels: good first issue, Added Project, Open source

#949 Added Home Automation
  IOT(Internet of Things)/Intermediate/Home Automation/Images/home_automation.JPG
  IOT(Internet of Things)/Intermediate/Home Automation/Images/home_automation.mp4
  IOT(Internet of Things)/Intermediate/Home Automation/README.md
  IOT(Internet of Things)/Intermediate/Home Automation/home_automation.cpp
  IOT(Internet of Things)/Intermediate/Home Automation/requirements.txt
  IOT(Internet of Things)/README.md
Labels: good first issue, Added Project
