Repository Kushal997-das/Project-Guidance, pull requests merged in 2023-01, with the labels that each got.

#769 Eth to Smart contract transaction
  Blockhain_Development/Basic/Snd_Ether/Send_Etehr.sol
  Blockhain_Development/Basic/Snd_Ether/readme.md
Labels: Added Project, SWOC, Medium

#783 added Bean eater loader
  Web Development/Basic/Bean Eater Loader/README.md
  Web Development/Basic/Bean Eater Loader/index.html
  Web Development/Basic/Bean Eater Loader/styles.css
Labels: Added Project, SWOC, Beginner

#787 Arithmetic Codes in Solidity
  Blockchain Development/Basic/Arithmetic/Avg/avg.sol
  Blockchain Development/Basic/Arithmetic/Avg/readme.md
  Blockchain Development/Basic/Arithmetic/Cube/cube.sol
  Blockchain Development/Basic/Arithmetic/Cube/readme.md
  Blockchain Development/Basic/Arithmetic/Even_Odd/even.sol
  Blockchain Development/Basic/Arithmetic/Even_Odd/readme.md
  Blockchain Development/Basic/Arithmetic/Prime_Check/prime.sol
  Blockchain Development/Basic/Arithmetic/Prime_Check/readme.md
  Blockchain Development/Basic/Arithmetic/Reverse/readme.md
  Blockchain Development/Basic/Arithmetic/Reverse/reverse.sol
  Blockchain Development/Basic/Arithmetic/Sum_of_Digit/readme.md
  Blockchain Development/Basic/Arithmetic/Sum_of_Digit/sum.sol
  Blockchain Development/Basic/Arithmetic/Swap/readme.md
  Blockchain Development/Basic/Arithmetic/Swap/swap.sol
  Blockchain Development/Basic/Arithmetic/exponent/expo.sol
  Blockchain Development/Basic/Arithmetic/exponent/readme.md
  Blockchain Development/Basic/Arithmetic/greatestofThree/got.sol
  Blockchain Development/Basic/Arithmetic/greatestofThree/readme.md
Labels: Added Project, SWOC, Beginner

#798 Gravity project added issue #795
  Desktop Application/Basic/Python/Gravity/Gravity.py
  Desktop Application/Basic/Python/Gravity/README.md
  Desktop Application/Basic/Python/Gravity/astronaut.ico
  Desktop Application/Basic/Python/Gravity/astronaut1.png
  Desktop Application/Basic/Python/Gravity/astronaut2.png
  Desktop Application/Basic/Python/Gravity/bg.png
  Desktop Application/Basic/Python/Gravity/demo.png
Labels: Added Project, SWOC, Beginner

#806 Updated Wed development readme
  Web Development/README.md
Labels: Added Project, SWOC, Beginner

#796 Added Uber Analysis #792
  Machine Learning and Data Science/Basic/Uber Analysis/My Uber Drives - 2016.csv
  Machine Learning and Data Science/Basic/Uber Analysis/README.md
  Machine Learning and Data Science/Basic/Uber Analysis/Uber Analysis.ipynb
  Machine Learning and Data Science/Basic/Uber Analysis/Uber Analysis.py
Labels: Added Project, SWOC, Beginner

#801 Zomato Landing Page Added
  Web Development/Basic/Zomato-Landing-Page/README.md
  Web Development/Basic/Zomato-Landing-Page/images/appleStore.png
  Web Development/Basic/Zomato-Landing-Page/images/collection1.jpg
  Web Development/Basic/Zomato-Landing-Page/images/collection2.jpg
  Web Development/Basic/Zomato-Landing-Page/images/collection3.jpg
  Web Development/Basic/Zomato-Landing-Page/images/collection4.jpg
  Web Development/Basic/Zomato-Landing-Page/images/heroSectionBackground.png
  Web Development/Basic/Zomato-Landing-Page/images/heroSectionLogo.png
  Web Development/Basic/Zomato-Landing-Page/images/item1.png
  Web Development/Basic/Zomato-Landing-Page/images/item2.png
  Web Development/Basic/Zomato-Landing-Page/images/item3.png
  Web Development/Basic/Zomato-Landing-Page/images/item4.png
  Web Development/Basic/Zomato-Landing-Page/images/logo.png
  Web Development/Basic/Zomato-Landing-Page/images/mobileBanner.png
  Web Development/Basic/Zomato-Landing-Page/images/playStore.png
  Web Development/Basic/Zomato-Landing-Page/index.html
  Web Development/Basic/Zomato-Landing-Page/styles.css
Labels: Added Project, SWOC, Medium

#813 Adding React E-Commerce App
  Web Development/Advanced/iiwotshi-E-Commerce Website/.gitignore
  Web Development/Advanced/iiwotshi-E-Commerce Website/README.md
  Web Development/Advanced/iiwotshi-E-Commerce Website/package.json
  Web Development/Advanced/iiwotshi-E-Commerce Website/public/index.html
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/App.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Announcement.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Categories.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/CategoryItem.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Footer.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Navbar.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Product.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Products.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/components/Slider.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/data.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/index.js
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/pages/Cart.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/pages/Home.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/pages/Login.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/pages/Product.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/pages/ProductList.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/pages/Register.jsx
  Web Development/Advanced/iiwotshi-E-Commerce Website/src/responsive.js
  Web Development/Advanced/iiwotshi-E-Commerce Website/yarn.lock
  Web Development/README.md
Labels: Added Project, SWOC, Advance

#816 Wine quality prediction
  Machine Learning and Data Science/Basic/Wine Quality Prediction/02- Wine_quality_prediction.ipynb
  Machine Learning and Data Science/Basic/Wine Quality Prediction/README.md
  Machine Learning and Data Science/Basic/Wine Quality Prediction/WineQT.csv
Labels: Added Project, SWOC, Beginner

#821 added AI readme
  Artificial Intelligence/README.md
Labels: documentation, SWOC, Beginner

#827 Red Wine Quality Prediction
  Machine Learning and Data Science/Basic/Red Wine Quality Prediction/Red_Wine_Quality.ipynb
  Machine Learning and Data Science/Basic/Red Wine Quality Prediction/readme.md
  Machine Learning and Data Science/Basic/Red Wine Quality Prediction/winequality-red.csv
  Machine Learning and Data Science/README.md
Labels: Added Project, SWOC, Beginner

#829 Added weight-convertor project
  Web Development/Basic/Weight-Converter/README.md
  Web Development/Basic/Weight-Converter/index.html
  Web Development/Basic/Weight-Converter/main.css
Labels: Added Project, SWOC, Beginner
