Repository Kushal997-das/Project-Guidance, pull requests merged in 2023-02, with the labels that each got.

#838 Service providing Website added
  Web Development/Basic/Service providing website/README.md
  Web Development/Basic/Service providing website/Screenshot (225).png
  Web Development/Basic/Service providing website/Screenshot (228).png
  Web Development/Basic/Service providing website/asset-manifest.json
  Web Development/Basic/Service providing website/favicon.ico
  Web Development/Basic/Service providing website/index.html
  Web Development/Basic/Service providing website/logo192.png
  Web Development/Basic/Service providing website/logo512.png
  Web Development/Basic/Service providing website/manifest.json
  Web Development/Basic/Service providing website/robots.txt
  Web Development/Basic/Service providing website/static/css/main.1b2aab57.css
  Web Development/Basic/Service providing website/static/css/main.1b2aab57.css.map
  Web Development/Basic/Service providing website/static/js/main.5647f6b2.js
  Web Development/Basic/Service providing website/static/js/main.5647f6b2.js.license.txt
  Web Development/Basic/Service providing website/static/js/main.5647f6b2.js.map
  Web Development/Basic/Service providing website/static/media/charu.04e3a964e2c7344a61b2.jpg
  Web Development/Basic/Service providing website/static/media/dark analytics-bro.58fbe2beadaeb9a2e32fe3bb053bd25f.svg
  Web Development/Basic/Service providing website/static/media/dashboard.9400979f15f1286de109.png
  Web Development/Basic/Service providing website/static/media/dhee.a928b2e9cb17f6a22087.jpg
  Web Development/Basic/Service providing website/static/media/financial-calculator.86e19a3716eb4ebcd921.jfif
  Web Development/Basic/Service providing website/static/media/ha.073d02fe4e40c8df22f8.jpg
  Web Development/Basic/Service providing website/static/media/kri.fdf329aaebb02f60cb0d.jpg
  Web Development/Basic/Service providing website/static/media/logo (3).b84a765c7dbe3b9cd5db.png
  Web Development/Basic/Service providing website/static/media/msg-app.cadf1cd82d24b5a9b379.png
  Web Development/Basic/Service providing website/static/media/open source-cuate.3508b9d510bac5174703ba628e7025f6.svg
  Web Development/Basic/Service providing website/static/media/sa.5c57fea1652542d8667f.jpg
  Web Development/Basic/Service providing website/static/media/sh.f1debd12b8a43318ad80.jpg
  Web Development/Basic/Service providing website/static/media/social-app.3f432ef84edb03da263a.png
  Web Development/Basic/Service providing website/static/media/source hub.110c50bd9a5d05aa1e66.png
  Web Development/Basic/Service providing website/static/media/to-do-app.eaf1dc0a18f186724061.png
  Web Development/Basic/Service providing website/static/media/why-us.0b38b56dc7642af4e0af.png
  Web Development/README.md
Labels: Added Project, SWOC, Medium

#839 Added restaurant
  Web Development/Basic/Online Restaurant/README.md
  Web Development/Basic/Online Restaurant/css/animate.min.css
  Web Development/Basic/Online Restaurant/css/bootstrap.min.css
  Web Development/Basic/Online Restaurant/css/font-awesome.min.css
  Web Development/Basic/Online Restaurant/css/nivo-lightbox.css
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/close.png
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/close@2x.png
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/default.css
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/loading.gif
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/loading@2x.gif
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/next.png
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/next@2x.png
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/prev.png
  Web Development/Basic/Online Restaurant/css/nivo_themes/default/prev@2x.png
  Web Development/Basic/Online Restaurant/css/style.css
  Web Development/Basic/Online Restaurant/fonts/FontAwesome.otf
  Web Development/Basic/Online Restaurant/fonts/fontawesome-webfont.eot
  Web Development/Basic/Online Restaurant/fonts/fontawesome-webfont.svg
  Web Development/Basic/Online Restaurant/fonts/fontawesome-webfont.ttf
  Web Development/Basic/Online Restaurant/fonts/fontawesome-webfont.woff
  Web Development/Basic/Online Restaurant/fonts/fontawesome-webfont.woff2
  Web Development/Basic/Online Restaurant/images/chef1.svg
  Web Development/Basic/Online Restaurant/images/chef2.svg
  Web Development/Basic/Online Restaurant/images/chef3.svg
  Web Development/Basic/Online Restaurant/images/footer-bg.jpg
  Web Development/Basic/Online Restaurant/images/gallery-img1.jpg
  Web Development/Basic/Online Restaurant/images/gallery-img2.jpg
  Web Development/Basic/Online Restaurant/images/gallery-img3.jpg
  Web Development/Basic/Online Restaurant/images/gallery-img4.jpg
  Web Development/Basic/Online Restaurant/images/gallery-img5.jpg
  Web Development/Basic/Online Restaurant/images/home-bg.jpg
  Web Development/Basic/Online Restaurant/index.html
  Web Development/Basic/Online Restaurant/js/bootstrap.min.js
  Web Development/Basic/Online Restaurant/js/custom.js
  Web Development/Basic/Online Restaurant/js/jquery.js
  Web Development/Basic/Online Restaurant/js/jquery.parallax.js
  Web Development/Basic/Online Restaurant/js/nivo-lightbox.min.js
  Web Development/Basic/Online Restaurant/js/smoothscroll.js
  Web Development/Basic/Online Restaurant/js/wow.min.js
  Web Development/README.md
Labels: Added Project, SWOC, Medium

#845 Food Menu cart
  Web Development/Basic/Food Menu Cart/README.md
  Web Development/Basic/Food Menu Cart/css/demo.css
  Web Development/Basic/Food Menu Cart/css/style.css
  Web Development/Basic/Food Menu Cart/img/background.webp
  Web Development/Basic/Food Menu Cart/img/plate__chicken-salad.webp
  Web Development/Basic/Food Menu Cart/img/plate__french-fries.webp
  Web Development/Basic/Food Menu Cart/img/plate__salmon-vegetables.webp
  Web Development/Basic/Food Menu Cart/img/plate__spaghetti-meat-sauce.webp
  Web Development/Basic/Food Menu Cart/img/plate__tortellini.webp
  Web Development/Basic/Food Menu Cart/index.html
  Web Development/Basic/Food Menu Cart/js/script.js
Labels: Added Project, SWOC, Medium

#847 added Blockchain readme
  Blockchain Development/README.md
  Blockchain Development/readme.md
Labels: documentation, SWOC, Beginner

#849 Titanic Survival Prediction
  Machine Learning and Data Science/Basic/Titanic_Survival_Prediction/README.md
  Machine Learning and Data Science/Basic/Titanic_Survival_Prediction/Titanic_Survival.ipynb
  Machine Learning and Data Science/Basic/Titanic_Survival_Prediction/train.csv
Labels: Added Project, SWOC, Beginner

#854 Added Iot readme
  IOT(Internet of Things)/README.md
Labels: documentation, enhancement, SWOC, Beginner

#860 Readme updated
  Artificial Intelligence/README.md
  Blockchain Development/README.md
  Desktop Application/README.md
  Machine Learning and Data Science/README.md
  Mobile Applications/README.md
  Web Development/README.md
Labels: documentation, enhancement, SWOC, Beginner

#856 Netflix Landing Page Clone
  Web Development/Basic/Netflix Landing Page/README.md
  Web Development/Basic/Netflix Landing Page/index.html
  Web Development/Basic/Netflix Landing Page/script.js
  Web Development/Basic/Netflix Landing Page/style.css
  Web Development/README.md
Labels: Added Project, SWOC, Medium

#859 Postman Clone
  Web Development/Intermediate/postman clone/404.html
  Web Development/Intermediate/postman clone/Readme.md
  Web Development/Intermediate/postman clone/index.html
  Web Development/Intermediate/postman clone/script.js
  Web Development/Intermediate/postman clone/styles.css
  Web Development/README.md
Labels: Added Project, SWOC, Medium
