Repository Kushal997-das/Project-Guidance, pull requests merged in 2024-10, with the labels that each got.

#1404 Update All README Files for Clarity
  Artificial Intelligence/README.md
  Desktop Application/README.md
  IOT(Internet of Things)/README.md
  Machine Learning and Data Science/README.md
  Mobile Applications/README.md
  README.md
  Web Development/README.md
Labels: documentation, hacktoberfest-accepted, level1, Approved! ✅, hacktoberfest2024, gssoc-extd

#1416 Added Blinkit Clone - Basic Web Development Project (#1368)
  Web Development/Basic/Blinkit-Clone/README.md
  Web Development/Basic/Blinkit-Clone/index.html
  Web Development/Basic/Blinkit-Clone/resources.txt
  Web Development/Basic/Blinkit-Clone/style.css
  Web Development/README.md
Labels: Project Added! 🚀, Approved! ✅, hacktoberfest2024, gssoc-extd

#1457 Added Animated Footer Part #1410
  website/Facebk.png
  website/Github.png
  website/index.html
  website/instagram.png
  website/style.css
  website/twitter.png
Labels: enhancement, level1, Approved! ✅, hacktoberfest2024, gssoc-extd

#1425 Refactored Age Calculation Logic with Improved Date Handling
  Desktop Application/Basic/Python/Age calculator/age.py
Labels: hacktoberfest-accepted, level1, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1500 Readme.md files update now
  Artificial Intelligence/README.md
  Desktop Application/README.md
  IOT(Internet of Things)/README.md
  Machine Learning and Data Science/README.md
  Mobile Applications/README.md
  Web Development/README.md
Labels: documentation, Fixed Bug, level1, hacktoberfest2024, gssoc-ext

#1512 Update README.md of ML and DS
  Machine Learning and Data Science/README.md
Labels: Changes-required, hacktoberfest2024, gssoc-ext

#1461 AI Image Generator
  Web Development/Intermediate/AI Image Generator/.gitignore
  Web Development/Intermediate/AI Image Generator/README.md
  Web Development/Intermediate/AI Image Generator/components.json
  Web Development/Intermediate/AI Image Generator/eslint.config.js
  Web Development/Intermediate/AI Image Generator/index.html
  Web Development/Intermediate/AI Image Generator/jsconfig.json
  Web Development/Intermediate/AI Image Generator/package-lock.json
  Web Development/Intermediate/AI Image Generator/package.json
  Web Development/Intermediate/AI Image Generator/postcss.config.js
  Web Development/Intermediate/AI Image Generator/public/vite.svg
  Web Development/Intermediate/AI Image Generator/server/.gitignore
  Web Development/Intermediate/AI Image Generator/server/genrateImageController.js
  Web Development/Intermediate/AI Image Generator/server/index.js
  Web Development/Intermediate/AI Image Generator/server/package-lock.json
  Web Development/Intermediate/AI Image Generator/server/package.json
  Web Development/Intermediate/AI Image Generator/src/App.css
  Web Development/Intermediate/AI Image Generator/src/App.jsx
  Web Development/Intermediate/AI Image Generator/src/assets/react.svg
  Web Development/Intermediate/AI Image Generator/src/components/ui/3d-card.jsx
  Web Development/Intermediate/AI Image Generator/src/components/ui/placeholders-and-vanish-input.jsx
  Web Development/Intermediate/AI Image Generator/src/components/ui/wavy-background.jsx
  Web Development/Intermediate/AI Image Generator/src/index.css
  Web Development/Intermediate/AI Image Generator/src/lib/utils.js
  Web Development/Intermediate/AI Image Generator/src/main.jsx
  Web Development/Intermediate/AI Image Generator/src/utils/constants.js
  Web Development/Intermediate/AI Image Generator/tailwind.config.js
  Web Development/Intermediate/AI Image Generator/vite.config.js
  Web Development/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level2, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1482 Onclick listner on the Domains names and table of content cards
  website/index.html
Labels: documentation, level1, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1477 Added Voting.sol and Raffle.sol to Blockchain/Intermediate
  Blockchain Development/Intermediate/Raffle/Raffle.sol
  Blockchain Development/Intermediate/Raffle/readme.md
  Blockchain Development/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, Changes-required, hacktoberfest2024, WoB, gssoc-ext

#1531 Fix: Prevent addition of empty or whitespace-only tasks
  Desktop Application/Basic/Python/To-Do List/main.py
Labels: documentation, Level0, hacktoberfest2024, gssoc-ext

#1499 RFID Door Lock System with Arduino
  IOT(Internet of Things)/Intermediate/RFID Door Lock System/Circuit.png
  IOT(Internet of Things)/Intermediate/RFID Door Lock System/RFID_LOCK_PROJECT.mp4
  IOT(Internet of Things)/Intermediate/RFID Door Lock System/main.ino
  IOT(Internet of Things)/Intermediate/RFID Door Lock System/readme.md
  IOT(Internet of Things)/Intermediate/RFID Door Lock System/scan/scan.ino
  IOT(Internet of Things)/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level1, hacktoberfest2024, gssoc-ext

#1427 added hackathon tracker
  Web Development/Intermediate/Hackathon Tracker/README.md
  Web Development/Intermediate/Hackathon Tracker/index.html
  Web Development/Intermediate/Hackathon Tracker/screenshot.PNG
  Web Development/Intermediate/Hackathon Tracker/script.js
  Web Development/Intermediate/Hackathon Tracker/style.css
  Web Development/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level2, hacktoberfest2024, gssoc-ext

#1548 added garden planner website
  Web Development/Intermediate/Garden Planner/GardenPlanner.PNG
  Web Development/Intermediate/Garden Planner/README.md
  Web Development/Intermediate/Garden Planner/index.html
  Web Development/Intermediate/Garden Planner/script.js
  Web Development/Intermediate/Garden Planner/styles.css
  Web Development/README.md
Labels: Changes-required, hacktoberfest2024, gssoc-ext

#1559 Added Music Popularity Prediction | ML & DS project
  Machine Learning and Data Science/Intermediate/Music Popularity Prediction/Music Popularity Prediction.ipynb
  Machine Learning and Data Science/Intermediate/Music Popularity Prediction/README.md
  Machine Learning and Data Science/Intermediate/Music Popularity Prediction/Spotify_data.csv
  Machine Learning and Data Science/README.md
Labels: hacktoberfest-accepted, level3, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1575 Added Favicon.
  website/favicon.png
  website/index.html
Labels: documentation, hacktoberfest-accepted, level1, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1594 Updated spelling errors
  Desktop Application/Basic/C++/Calender/README.md
Labels: documentation, good first issue, hacktoberfest-accepted, Level0, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1599 Text_Summarization_Using_Transformers
  Machine Learning and Data Science/Basic/Text Summarization Using Transformers/Readme.md
  Machine Learning and Data Science/Basic/Text Summarization Using Transformers/Text_Summarization_Using_Transformers.ipynb
  Machine Learning and Data Science/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level2, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1576 Adding Customer Churn Prediction Model
  Machine Learning and Data Science/Intermediate/Customer Churn Prediction/README.md
  Machine Learning and Data Science/Intermediate/Customer Churn Prediction/data/Churn_Modelling.csv
  Machine Learning and Data Science/Intermediate/Customer Churn Prediction/notebook/Model.ipynb
  Machine Learning and Data Science/Intermediate/Customer Churn Prediction/saved_models/Gradient_Boosting_Classifier.joblib
  Machine Learning and Data Science/Intermediate/Customer Churn Prediction/saved_models/scaler.joblib
  Machine Learning and Data Science/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level2, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext
