Repository Kushal997-das/Project-Guidance, pull requests merged in 2024-07, with the labels that each got.

#1235 Added Selenium Automated game playing bot
  Desktop Application/Basic/Python/Selenium-Automated-Cookie-PlayerGame/README.md
  Desktop Application/Basic/Python/Selenium-Automated-Cookie-PlayerGame/main.py
  Desktop Application/README.md
Labels: Added Project, gssoc, level1

#1275 Update README.md [Fixing the Links direction]
  Desktop Application/README.md
Labels: Fixed Bug

#1248 Updated Web Dev Project (Weather App)
  Web Development/Basic/Weather App/Icons/pine-watt-2Hzmz15wGik-unsplash.jpg
  Web Development/Basic/Weather App/Icons/screenshot.png
  Web Development/Basic/Weather App/README.md
  Web Development/Basic/Weather App/app.js
  Web Development/Basic/Weather App/images/Screenshot from 2024-06-28 15-51-33.png
  Web Development/Basic/Weather App/images/Screenshot from 2024-06-28 15-51-45.png
  Web Development/Basic/Weather App/index.html
  Web Development/Basic/Weather App/style.css
Labels: Added Project, gssoc, level1

#1252 Amazon landing page
  Web Development/Basic/Amazon-Clone/README.MD
  Web Development/Basic/Amazon-Clone/images/amazon_logo.png
  Web Development/Basic/Amazon-Clone/images/amazonclonepic.PNG
  Web Development/Basic/Amazon-Clone/images/amazonlogin.jpg
  Web Development/Basic/Amazon-Clone/images/box1_image.jpg
  Web Development/Basic/Amazon-Clone/images/box2_image.jpg
  Web Development/Basic/Amazon-Clone/images/box3_image.jpg
  Web Development/Basic/Amazon-Clone/images/box4_image.jpg
  Web Development/Basic/Amazon-Clone/images/box5_image.jpg
  Web Development/Basic/Amazon-Clone/images/box6_image.jpg
  Web Development/Basic/Amazon-Clone/images/box7_image.jpg
  Web Development/Basic/Amazon-Clone/images/box8_image.jpg
  Web Development/Basic/Amazon-Clone/images/hero_image.jpg
  Web Development/Basic/Amazon-Clone/images/loginpage.PNG
  Web Development/Basic/Amazon-Clone/images/signuppage.PNG
  Web Development/Basic/Amazon-Clone/index.html
  Web Development/Basic/Amazon-Clone/page02.css
  Web Development/Basic/Amazon-Clone/page02.html
  Web Development/Basic/Amazon-Clone/page03.css
  Web Development/Basic/Amazon-Clone/page03.html
  Web Development/Basic/Amazon-Clone/styless.css
  Web Development/Basic/README.md
  Web Development/README.md
Labels: Added Project, gssoc, level1

#1277 RGB Color Slider
  Web Development/Basic/RGB Color Slider/README.md
  Web Development/Basic/RGB Color Slider/index.html
  Web Development/Basic/RGB Color Slider/script.js
  Web Development/Basic/RGB Color Slider/style.css
  Web Development/README.md
Labels: Added Project, gssoc, level1

#1272 Added Back-To-Top Button
  website/app.js
  website/index.html
  website/style.css
Labels: enhancement, gssoc, level1

#1316 changes
  Documents/LogoWithoutText.ico
  Documents/logo.png
  website/index.html
Labels: enhancement, good first issue, gssoc, level1

#1321 Added Machine Learning Model for IPL Outcome Prediction"
  Machine Learning and Data Science/Advanced/EXPLORATORY DATA ANALYSIS (SPORTS)/Sports.ipynb
Labels: enhancement, gssoc, level1
