Repository Kushal997-das/Project-Guidance, pull requests merged in 2024-11, with the labels that each got.

#1591 Added Healta(Mental Health Website) to basic web development project
  Web Development/Basic/Healta-mental health website/Depr.jpg
  Web Development/Basic/Healta-mental health website/Healta.jpg
  Web Development/Basic/Healta-mental health website/WhatsApp_Image_2023-09-29_at_21.54.06_e754a1ed-removebg-preview (1).png
  Web Development/Basic/Healta-mental health website/about us .css
  Web Development/Basic/Healta-mental health website/about us.html
  Web Development/Basic/Healta-mental health website/anx.jpg
  Web Development/Basic/Healta-mental health website/bipolar.jpg
  Web Development/Basic/Healta-mental health website/cardout.jpg
  Web Development/Basic/Healta-mental health website/dissocial.jpg
  Web Development/Basic/Healta-mental health website/dont_panic.jpg
  Web Development/Basic/Healta-mental health website/find_a_therapist.css
  Web Development/Basic/Healta-mental health website/find_a_therapist.html
  Web Development/Basic/Healta-mental health website/h.jpg
  Web Development/Basic/Healta-mental health website/index.css
  Web Development/Basic/Healta-mental health website/index.html
  Web Development/Basic/Healta-mental health website/joy.jpg
  Web Development/Basic/Healta-mental health website/man.jpg
  Web Development/Basic/Healta-mental health website/mental-health-removebg-preview.png
  Web Development/Basic/Healta-mental health website/ptsd.jpg
  Web Development/Basic/Healta-mental health website/readme.md
  Web Development/Basic/Healta-mental health website/resources.css
  Web Development/Basic/Healta-mental health website/resources.html
  Web Development/Basic/Healta-mental health website/scizo.jpg
  Web Development/Basic/Healta-mental health website/woman.jpg
  Web Development/Basic/Multiply JSP/.project
  Web Development/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level2, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1583 Addition of Maze Solver Application
  Desktop Application/Basic/Python/Maze Solver/Readme.md
  Desktop Application/Basic/Python/Maze Solver/main.py
  Desktop Application/README.md
Labels: Project Added! 🚀, hacktoberfest-accepted, level1, Status Update: Approved! ✅, hacktoberfest2024, gssoc-ext

#1616 add chatbot
  website/index.html
Labels: documentation, level1, Status Update: Approved! ✅, gssoc-ext
