Repository Kushal997-das/Project-Guidance, pull requests merged in 2024-06, with the labels that each got.

#1126 Update README.md
  Machine Learning and Data Science/Intermediate/To explore Business Analytics/README.md
Labels: documentation, gssoc

#1152 Update greetings.yml [Testing 6]
  .github/workflows/greetings.yml
Labels: Testing

#1112 Added auto commenting featue on new issue and pr
  .github/workflows/auto-comment-on-issue.yml
  .github/workflows/auto-comment-pr-raise.yml
Labels: Changes-required, gssoc, Level0

#1165 Landing page for the entire website, fully responsive and interactive
  website/app.js
  website/index.html
  website/input.css
  website/output.css
  website/particles.js
  website/particles.json
  website/style.css
  website/tailwind.config.js
Labels: Added Project, gssoc, level3

#1195 QUIZ Desktop Application
  Desktop Application/Basic/Python/Quiz_Application/README.md
  Desktop Application/Basic/Python/Quiz_Application/data.py
  Desktop Application/Basic/Python/Quiz_Application/images/false.png
  Desktop Application/Basic/Python/Quiz_Application/images/quiz.png
  Desktop Application/Basic/Python/Quiz_Application/images/quizlol.png
  Desktop Application/Basic/Python/Quiz_Application/images/right_and_wrong_answer.png
  Desktop Application/Basic/Python/Quiz_Application/images/true.png
  Desktop Application/Basic/Python/Quiz_Application/main.py
  Desktop Application/Basic/Python/Quiz_Application/players.csv
  Desktop Application/Basic/Python/Quiz_Application/question_model.py
  Desktop Application/Basic/Python/Quiz_Application/quiz_brain.py
  Desktop Application/Basic/Python/Quiz_Application/requirements.txt
  Desktop Application/Basic/Python/Quiz_Application/ui.py
  Desktop Application/README.md
Labels: Added Project, gssoc, level1

#1204 Added Loan Amount Prediction by using Machine Learning Project
  Machine Learning and Data Science/Intermediate/Loan Amount Prediction/Loan Amount Prediction.ipynb
  Machine Learning and Data Science/Intermediate/Loan Amount Prediction/Readme.md
  Machine Learning and Data Science/Intermediate/Loan Amount Prediction/test.csv
  Machine Learning and Data Science/Intermediate/Loan Amount Prediction/train.csv
  Machine Learning and Data Science/README.md
Labels: Added Project, gssoc, level2

#1221 Update greetings.yml
  .github/workflows/greetings.yml
Labels: Testing

#1192 Added Markdown Previewer
  Web Development/Basic/Markdown Previewer/index.html
  Web Development/Basic/Markdown Previewer/readme.md
  Web Development/Basic/Markdown Previewer/screenshot.png
  Web Development/Basic/Markdown Previewer/script.js
  Web Development/Basic/Markdown Previewer/styles.css
  Web Development/README.md
Labels: Added Project, gssoc, level1

#1232 Update greetings.yml
  .github/workflows/greetings.yml
Labels: Testing

#1227 Resolved Project Redirecting links Issue #1213
  Machine Learning and Data Science/README.md
Labels: documentation, enhancement, good first issue, gssoc

#1225 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue, gssoc
